### ISSUE TITLE
Twinning.Rmd cannot run on Windows on many of its lines

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#106]
Twinning.Rmd lines 116-119 cannot run on Windows

**Comment by Giappo** [comment]
Lines are:
df <- pirouette::pir_run(
  phylogeny = phylogeny,
  pir_params = pir_params
)

I changed it to:
if (rappdirs::app_dir()$os != "win") {
df <- pirouette::pir_run(
  phylogeny = phylogeny,
  pir_params = pir_params
)
}

Problem is that many lines after that actually depends on this call.
How do we deal with that?

**Comment by richelbilderbeek** [comment]
> How do we deal with that?
I'd suggest:

```
if (!windows) {
  # Do stuff
} else {
  # Create fake output
}
```

Fake output that breaks nothing is good enough.

**Comment by Giappo** [comment]
For now I put if statements all over the place (kind of what you suggested but with no fake outputs)

**Comment by richelbilderbeek** [comment]
Well done! 

Closing the Issue ...
