### ISSUE TITLE
Add "twinning_params" in "create_twin_tree" call in "pir_run"

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#108]
When creating the twin tree in pir_run (currently R.43) the argument "twinning_params" of the function "create_twin_tree" calls the default option.
I believe it is more correct to call the actual "twinning_params" provided by "pir_params". If so we can add an option to recall the "pir_params$alignment_params$rng_seed" if "pir_params$twinning_params$rng_seed" is set to something like "same_seed". This could provide the solution to issue #84

**Comment by Giappo** [comment]
I will fix this myself. I hope @richelbilderbeek agrees with my idea.

**Comment by richelbilderbeek** [comment]
Looks like a good idea to me as well!

Taking the liberty to close this Issue :rainbow:
