### ISSUE TITLE
Make twinning.Rmd run

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#109]
twinning.Rmd cannot run when calling pir_run after defining the experiments.
I suppose this is happening after I redefined alignment_params and/or twinning_params to accommodate, respectively, for the function "create_standard_mutation_rate" in place of a numeric mutation rate and "same_seed" in place of a number for "twinning_params$rng_seed".
I can't run it on windows even if i set:

```r
experiment_1 <- create_experiment(
  model_type = "generative",
  run_if = "always",
  do_measure_evidence = TRUE,
  inference_model = create_inference_model(
    tree_prior = create_bd_tree_prior(),
    mcmc = create_mcmc(chain_length = 3000, store_every = 1000)
  ),
  est_evidence_mcmc = create_nested_sampling_mcmc(epsilon = 100.0),
  beast2_options = create_beast2_options(rng_seed = 314)
)
experiments <- list(experiment_1, experiment_1)
```
I don't know exactly why. What I get is that I cannot do it because mcbette must run on Linux or Mac (which is weird, considering that I am using only generative model types).

If I run it on travis instead I get this error message:

```
Quitting from lines 116-123 (twinning.Rmd) 
Error: processing vignette 'twinning.Rmd' failed with diagnostics:
numbers of columns of arguments do not match
```

I commented the lines that are not working in order to push it to develop

**Comment by richelbilderbeek** [comment]
Note to self: may have been a remainder of #99, let's see if I can reproduce this ...

**Comment by richelbilderbeek** [comment]
The error message may have been a little earlier for Giappo, created #110.

**Comment by richelbilderbeek** [comment]
Works!

[twinning.pdf](https://github.com/richelbilderbeek/pirouette/files/2854489/twinning.pdf)
