### ISSUE TITLE
Improve dododo

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#11]
See [the dododo Issue](https://github.com/xl0418/dododo/issues/4).

I think @Giappo will volunteer to do so :+1:

(if not, sorry, just let me know)

**Comment by Giappo** [comment]
Hi Richel,

I think the best option is to remove the dependency on dododo because it is basically an empty package with a single function.
I will instead copy the razzo version of phylo2L inside pirouette.

**Comment by richelbilderbeek** [comment]
As agreed up: go ahead and merge it :+1: 

Closing this Issue...
