### ISSUE TITLE
Give an error on Windows when do_measure_evidence is TRUE

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#110]
This is a follow-up from #109.

When running one experiment:

```r
experiment_1 <- create_experiment(
  model_type = "generative",
  run_if = "always",
  do_measure_evidence = TRUE,
  # ...
)
```

when `do_measure_evidence` is `TRUE`, the evidence will be estimated by `mcbette`, thus a UNIX-only feature. Give an early error when `do_measure_evidence` is `TRUE` on Windows.

**Comment by richelbilderbeek** [comment]
I think @Giappo will like this one :+1:

**Comment by Giappo** [comment]
I can do this, I think, but I have one question: why do we want to measure evidence when the model_type == "generative"? I though that when you select "generative" you mean that there is only one possibility, i.e. the posterior are generated according to the same model (or combination of site_model, clock_model etc) used to simulate the alignments, ergo the (single) marginal likelihood weight would be always equal to one and there is no need to call mcbette. Am I wrong?

**Comment by richelbilderbeek** [comment]
You are completely right: with one model, the weight is always 1.0.

We need this when there are more models into play, say:

 * 1 generative model (say, JC69, strict, BD)
 * 3 candidates, with different site models

We'll be interested in the generative model and the best candidate model, as in our `razzo` paper.

Capice like that?

**Comment by Giappo** [comment]
Chi?

**Comment by Giappo** [comment]
> Capice like that?

Chi? :D

**Comment by richelbilderbeek** [comment]
My Italian may not be entirely correct :sunglasses: ...
