### ISSUE TITLE
Agree on the new razzo file naming proposal?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#113]
Currently, file naming is like this:

Filename|Description
-------------|---------------------------------------
`parameters.RDa`|the parameter file
[TODO]`mbd.tree`|the true MBD tree
`mbd.fasta`|the true MBD alignment
`mbd.trees`|the posterior trees from `mbd.tree`
`mbd.log`|the posterior parameter estimates from `mbd.tree`
`mbd_marg_lik.csv`|the posterior's marginal likelihood from `mbd.tree`
`mbd_nltts.csv`|the nLTT statistic distribution between `mbd.tree` and `mbd.trees`
`bd.tree`|the twin BD tree
`bd.fasta`|the twin BD alignment
`bd.trees`|the posterior trees from `bd.tree`
`bd.log`|the posterior parameter estimates from `bd.tree`
`bd_marg_lik.csv`|the posterior's marginal likelihood from `bd.tree`
`bd_nltts.csv`|the nLTT statistic distribution between `bd.tree` and `bd.trees`

I suggest to use the `pirouette::create_twin_filename` conventions from now on, which converts `mbd` to `mbd_twin`.

Also, we need to add filenames for the generative and best candidate model. See below for an example.

@Giappo: agreed?

**Comment by richelbilderbeek** [comment]
New skool would be:

New skool:

Filename|Description
-------------|---------------------------------------
`parameters.RDa`|the parameter file
[TODO]`mbd.tree`|the true MBD tree
`mbd.fasta`|the true MBD alignment
`mbd_gen.trees`|the posterior trees from the true alignment, using the generative model
`mbd_gen.log`|the posterior parameter estimates from the true tree, using the generative model
`mbd_best.trees`|the posterior trees from the true tree, using best candidate model
`mbd_best.log`|the posterior parameter estimates from the true tree, using the best candidate model
`mbd_marg_lik.csv`|the evidences (aka marginal likelihoods) all models have for the true alignment 
`mbd_nltts_gen.csv`|the error between true tree and its posterior for the generative model
`mbd_nltts_best.csv`|the error between true tree and its posterior for the best candidate model
[TODO]`mbd_twin.tree`|the twin MBD tree
`mbd_twin.fasta`|the twin MBD alignment
`mbd_gen_twin.trees`|the posterior trees from the twin alignment, using the generative model
`mbd_gen_twin.log`|the posterior parameter estimates from the twin tree, using the generative model
`mbd_best_twin.trees`|the posterior trees from the twin tree, using best candidate model
`mbd_best_twin.log`|the posterior parameter estimates from the twin tree, using the best candidate model
`mbd_marg_lik_twin.csv`|the evidences (aka marginal likelihoods) all models have for the twin alignment 
`mbd_nltts_gen_twin.csv`|the error between twin tree and its posterior for the generative model
`mbd_nltts_best_twin.csv`|the error between twin tree and its posterior for the best candidate model

**Comment by Giappo** [comment]
I think that if we imagine to apply pirouette to a variety of specific-model-generated phylogenies (e.g. mbd, pbd, etc) it's necessary to change the nomenclature from "bd" to some combination that contains "modelname" + "twin".

The way in which we want to do it is a secondary order of problem and I agree that we should set a standard that must always be adopted, no matter what, by the same function, namely by "pirouette::create_twin_filename".

I see only two options here:
1: "modelname_filetype_twin.ext" (current version);
2: "modelname_twin_filetype.ext";

As far as I am concerned the first instance (first paragraph of this comment) is far more important than the second one (2nd paragraph of this comment). That said, I find option 2 to seem more logical. If you think it's too time-consuming and/or not important enough, I can stick to option 1, though.

**Comment by Giappo** [comment]
Once we take the decision I can take this issue and set all the filenames setting up "pirouette::create_twin_filename", if you want.

**Comment by richelbilderbeek** [comment]
I suggest to stick to the easier option 1 (keep it as it is), then maybe one rainy day to switch to option 2. Thanks!

If you agree, go ahead and close this Issue :+1:

**Comment by Giappo** [comment]
@richelbilderbeek one last question: are all the filenames already following the chosen convention or there is still some work to do?

**Comment by richelbilderbeek** [comment]
They follow the chosen convention since a couple of minutes :+1:

There is still some work to do, will add Issues now :grin:
