### ISSUE TITLE
Specify where errors are stored

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#115]
Currently, the `error_measure_params` only have a burn-in and error function:

```r
create_error_measure_params(
  burn_in_fraction = 0.1, 
  error_function = get_nltt_error_function()) 
{
  # ...
}
```

Add an argument, say `filename` that is `tempfile(fileext = ".csv")` by default.

Write a test that does a generative model run (no evidence calculation) to check if the specified file is created at that location).

**Comment by richelbilderbeek** [comment]
Hmmm, I specify it as high, as I could use it already for `razzo`. No need to rush though :rainbow:

**Comment by Giappo** [comment]
What do we want to store in this file?

**Comment by richelbilderbeek** [comment]
The errors, as a CSV, basically, a bunch of numbers :rainbow:

**Comment by Giappo** [comment]
How does this file differs from the df generated by pir_run?
If I only store errors, without keeping track of the setting that I used to generate them, how can I use them in the future?
Do we really need to store these in a file? It looks redundant, since the output of pir_run actually provides exactly this.
Is there something I am missing?

**Comment by richelbilderbeek** [comment]
Good point! Hmmm, I am unsure how redundant that is.. I suggest to lower priority until I have a better idea about it OK?

Just to answer your question: the `df` differs that it has one row per `df`; there are four `df`s instead of the one big one returned by `pir_run`.

**Comment by richelbilderbeek** [comment]
Still, usually I do have a good instinct on such things :male_detective: ...

**Comment by Giappo** [comment]
Ok @richelbilderbeek , I think I solved it. Please give it a look and tell me if it's done in the way you like. In case you want something different just let me know.

**Comment by richelbilderbeek** [comment]
AFAICS, looks great. Will close when I am sure :rainbow:

**Comment by richelbilderbeek** [comment]
Checked with `razzo`, works great! :+1:
