### ISSUE TITLE
Explain me why "model_type" and "run_if" are not redundant arguments

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#120]
I don't completely understand how this works.
If I open the create_experiment function I notice that "model_type" and "run_if" have 2 possible options each. So the possible combinations are four:

- "generative" and "always" (1);
- "candidate" and "always" (2);
- "generative" and "best_candidate" (3);
- "candidate" and "best_candidate" (4);

While some of them are obviously legit (1 and 4), I don't completely grasp the usage of the others. It might be that's just a personal problem of misunderstanding, though.

2 looks like you want to consider all candidates and run the analysis for all of them, without considering any evidence. Is it right?
3 for example seems to be not logical, but I feel that it might be in the light of the comment you added on #110 yesterday. Can it be that it might make sense in the light of two experiments run at the same time (e.g.  3 and 4)?

From what I see my impression is that, concerning #110, the error message should be thrown only in cases 3 and 4, where model selection actually takes place and mcbette should be called. In the state pirouette is now, though, i get the error for mcbette call also in case 2.

Please clarify me this, because even using the help section it's not really clear to me and if it's not clear to me, it's gonna be even less likely to be clear to a generic user.

**Comment by Giappo** [comment]
In all of this I forgot to mention the argument "do_measure_evidence" which adds another layer of complexity to the input structure.  Don't you want to measure evidence every time you're using "best_candidate"?
Don't we want to measure evidence every time we have more than one possible model?

I think you want to keep this because on windows systems we cannot measure evidence but, as a matter of fact, the only combination that can actually work on windows is:

model_type = "generative",
run_if = "always",
do_measure_evidence = FALSE

All the others seem to fail. For this reason I will do #110 making create_experiments throwing an error every time there is a setting different from this one.

**Comment by richelbilderbeek** [comment]
> 2 looks like you want to consider all candidates and run the analysis for all of them, without considering any evidence. Is it right?

That is indeed one of the ideas! Another idea is to do consider the evidence, and validate that the best candidate model has indeed/probably the lowest error. 

> 3 for example seems to be not logical, but I feel that it might be in the light of the comment you added on #110 yesterday. Can it be that it might make sense in the light of two experiments run at the same time (e.g. 3 and 4)?

Close! At the moment, this combination does not make sense: `best_candidate` selects the best candidate, event though the generative model may have a higher evidence. For `run_if == "best"` (not yet implemented), the best model of all models is run. 

...

**Comment by richelbilderbeek** [comment]
Clear? If yes, hit that funky Close button :grin: 

If you think I should put this in the doc now, create a new Issue :+1:
