### ISSUE TITLE
run_if == best_candidate and do_measure_evidence == FALSE makes no sense

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#128]

**Comment by Giappo** [comment]
I added the error message. Some tests fail for this reason. I don't completely get why.
Since you wrote them, and you are much more at ease with this complicated input structure than me, I think it could be easy for you to understand if such tests are to be modified or removed.
You can find them looking for #128 in the package

**Comment by richelbilderbeek** [comment]
Cool, will take a look :male_detective:

**Comment by richelbilderbeek** [comment]
The tests that broke showed @Giappo's work was great:

```
  experiment_candidate <- create_experiment(
    run_if = "best_candidate",
    # ...
  )
```

becomes, due to default value:

```
  experiment_candidate <- create_experiment(
    run_if = "best_candidate",
    do_measure_evidence = FALSE,
    # ...
  )
```

which indeed makes no sense. Changing the first code to:

```
  experiment_candidate <- create_experiment(
    run_if = "best_candidate",
    do_measure_evidence = TRUE,
    # ...
  )
```

fixes the test.

**Comment by richelbilderbeek** [comment]
Tests are fixed. Thanks @Giappo :+1:

Closing this Issue.
