### ISSUE TITLE
'create_twinning_params' should have a better default for 'method' 

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#134]
Currently, the `create_twinning_params` function has `method == random_tree` as a default argument. I suggest to make this any better replacement, as it already hurt my experiments for settling on what an ideal tree is (#127).

I suggest, after #133, to set the default to `stunning`, but feel free to take your favourite one.

**Comment by richelbilderbeek** [comment]
I think @Giappo would like this one :+1:

**Comment by Giappo** [comment]
I am still not sure this is a good idea, but if you like it I'll do it.
We need to talk with Rampal, because we risk to do a lot of work for nothing.

**Comment by richelbilderbeek** [comment]
Agree, we need to settle on the twinning. Except for that, I am happy with the default argument you added :+1:
