### ISSUE TITLE
Measure ESS of evidence estimation?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#139]
The estimation of the evidence (aka marginal likelihood) also has an Effective Sample Size (ESS). `beautier`, however, does not record this number, but it *is* there. We know that the `raket`/`razzo` experiments need an ESS of >200 to be reliable.

Should we measure the ESS of the evidence estimation?

I'd say yes.

If an ESS of >200 also holds in this context, I do not know, but I feel yes.

@Giappo: what do you think?

**Comment by Giappo** [comment]
@richelbilderbeek I think it can be done, if we need it.
Don't you think that this should be part of the package that actually takes care of the marginal likelihood estimation, aka "mcbette"?

**Comment by richelbilderbeek** [comment]
No, kill Issues with rule in #236
