### ISSUE TITLE
razzo: collect_nltt_stats

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#147]
Depends on:

 * [x] me pushing things to `develop`

This function is back from `v0.4`. It needs to work again. The raw data needed is there in `inst/extdata/etc...`.

**Comment by richelbilderbeek** [comment]
I think @Giappo would enjoy fixing his own work :+1:

**Comment by Giappo** [comment]
How do you create the file "nltt_stats"?

**Comment by richelbilderbeek** [comment]
By merging all these files 

```
mbd_nltts_gen.csv
mbd_nltts_best.csv
mbd_nltts_gen_twin.csv
mbd_nltts_best_twin.csv
```

in all folders to a data frame as specified in the test.

Will that work?

**Comment by Giappo** [comment]
What functions creates these files?

**Comment by richelbilderbeek** [comment]
(sorry, rush!)

`utils::write.csv` in a loop over experiments somewhere :rainbow:

**Comment by Giappo** [comment]
I suppose you meant save_errors_to_file(df = df, pir_params = pir_params) at the end of pir_run, in the pirouette package.
For some reason the call of pir_run inside run_razzo creates these files in which "clock model" and "site model" are different respect to the actual names you can find under pir_params$alignment_params$site_model$name and (I suppose) under pir_params$alignment_params$clock_model$name. For example in pir_params the site_model is called JC69 whereas in the results file is called jc69. This makes me think that there is probably something very weird goin on

**Comment by Giappo** [comment]
> By merging all these files
> 
> ```
> mbd_nltts_gen.csv
> mbd_nltts_best.csv
> mbd_nltts_gen_twin.csv
> mbd_nltts_best_twin.csv
> ```
> in all folders to a data frame as specified in the test.
> 
> Will that work?

What function does perform this operation?

**Comment by Giappo** [comment]
@richelbilderbeek 
The nltt files in the current form only contain these info:
1) errors;
2) "gen" or "best";
3) "twin" or "true";
test-collect_nltt_stats instead requires more information, like "clock_model", "site_model", "gen_model".
This information is not present in the content of the "mbd_nltt_*.csv" file nor in its name.
I tried to retrieve it from the parameters.RDa but it's impossible, as all the candidates are saved and I don't know which ones then becomes the best.
I suggest to operate within pirouette and save these files providing more information. Do you agree?

**Comment by richelbilderbeek** [comment]
Agreed! :+1:

**Comment by Giappo** [comment]
The same problem seems to happen also concerning the esses. Maybe I can solve both problems if I can somehow retrieve the information about which is the best model. Do you know in what files can I find this?

**Comment by richelbilderbeek** [comment]
The best model can be found in `mbd_marg_liks.csv` and `mbd_marg_liks_twin.csv`. It's a bit clumsy, but I also do so somewhere. Be aware of NA's in the weights!

**Comment by Giappo** [comment]
Ok, done. Where can I find the gen model instead?

**Comment by richelbilderbeek** [comment]
Both generative and candidate models are in there. By convention, the first row is always the generative one.

**Comment by richelbilderbeek** [comment]
The nLTT files are now -indeed- weird. It would be good if more info would be added to them :rainbow:

**Comment by Giappo** [comment]
Oh Richel,

I've seen that in "test-collect_nltt_stats" at some point you ask for 

expect_true(is.factor(df$inference_model))
expect_true(is.factor(df$inference_model_weight))

In what files can I retrieve these information?

**Comment by richelbilderbeek** [comment]
That would be weird, this

```r
expect_true(is.factor(df$inference_model))
expect_true(is.factor(df$inference_model_weight))
```

would belong to an evidence file. No idea what happened there, just delete it :+1:

**Comment by Giappo** [comment]
Does this mean that we have to add something similar in "test-collect_marg_liks"?

**Comment by richelbilderbeek** [comment]
Sounds like a plan :+1:

**Comment by richelbilderbeek** [comment]
Looks beautiful:

```
>   filenames <- collect_nltt_stats()
> filenames
  lambda   mu nu   q seed crown_age cond site_model clock_model  tree_prior gen_model best_or_gen     nltt_1    nltt_2    nltt_3     nltt_4
1    0.2 0.15  1 0.1    1        15    1       JC69      strict birth_death        bd        best 0.17303918 0.2577076 0.2511119 0.24967786
2    0.2 0.15  1 0.1    1        15    1       JC69      strict birth_death       mbd        best 0.18445560 0.2787587 0.2799271 0.27766816
3    0.2 0.15  1 0.1    1        15    1       JC69      strict birth_death        bd         gen 0.17303918 0.2634803 0.2609414 0.25384695
4    0.2 0.15  1 0.1    1        15    1       JC69      strict birth_death       mbd         gen 0.18445560 0.2497180 0.2430567 0.24361998
5    0.2 0.15  1 0.1    2        15    1        GTR      strict birth_death        bd        best 0.06124832 0.1587821 0.1574942 0.13491754
6    0.2 0.15  1 0.1    2        15    1        GTR      strict birth_death       mbd        best 0.04515716 0.1125983 0.1096313 0.07935964
7    0.2 0.15  1 0.1    2        15    1       JC69      strict birth_death        bd         gen 0.06124832 0.1541951 0.1461157 0.15392331
8    0.2 0.15  1 0.1    2        15    1       JC69      strict birth_death       mbd         gen 0.04515716 0.1423950 0.1300571 0.14809135
```
