### ISSUE TITLE
razzo: collect_marg_liks

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#148]
Depends on:

 * [x] me pushing things to `develop`

This function is back from `v0.4`. It needs to work again. The raw data needed is there in `inst/extdata/etc...`.

**Comment by richelbilderbeek** [comment]
I think @Giappo would enjoy fixing his own work :+1:

**Comment by Giappo** [comment]
Where can I find the marg_liks files? In the results folder they're not present...

**Comment by richelbilderbeek** [comment]
Each `data` folder has `mbd_marg_lik.csv` and `mbd_marg_lik_twin.csv`. Goal of `collect_marg_liks` is to combine these and write these to the results folder. 

Helpful?

**Comment by Giappo** [comment]
They are in the razzo/inst/extdata/ folder, not in the data folder. Plus they are all together and not split according to the folder system, which is "razzo_project/data/lambda-mu-nu-q/seed/"
We need to rework all of this

**Comment by richelbilderbeek** [comment]
I think all we changed was from using `razzo_project/data/lambda-mu-nu-q/seed/inference_model` to `razzo_project/data/lambda-mu-nu-q/seed`. So, yes indeed, there is some rework :+1:

**Comment by richelbilderbeek** [comment]
Well done :1st_place_medal:
