### ISSUE TITLE
razzo: collect_esses

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#149]
Depends on:

 * [x] me pushing things to `develop`

This function is back from `v0.4`. It needs to work again. The raw data needed is there in `inst/extdata/etc...`.

**Comment by richelbilderbeek** [comment]
I think @Giappo would enjoy fixing his own work :+1:

**Comment by Giappo** [comment]
In tracerer::calc_esses one argument is called "sample_interval". I have to retrieve its value from pir_params.
Where can I find the right one?

**Comment by richelbilderbeek** [comment]
I think `pir_params$experiments[[1]]$inference_model$mcmc$store_every` is where the love is :+1:

**Comment by richelbilderbeek** [comment]
Good stuff :+1:
