### ISSUE TITLE
pirouette on Peregrine gives error 'Invalid cross-device link'

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#152]
When creating the figures for the pirouette article on Peregrine, I get the following message: 
```
Error: file.exists(output_log_filename) is not TRUE
In addition: Warning messages:
1: In file.rename(from = from, to = output_log_filename) :
  cannot rename file 'file241a033e63bb0.log' to '/local/tmp/RtmpyBOOr7/file241a021232f4e.log', reason 'Invalid cross-device link'
2: In file.rename(from = from, to = to) :
  cannot rename file 'file241a033e63bb0.trees' to '/local/tmp/RtmpyBOOr7/file241a013575c6a.trees', reason 'Invalid cross-device link'
Execution halted
```

This hints that there is a problem with the location of temp files.

Workaround is simple: specify all paths of all temp files.

**Comment by Giappo** [comment]
I tried to install pirouette on Peregrine but I keep on getting an error when installing the dependency: "Rmpfr".
Are you getting the same error?
I attach a copy of the error message I am getting:

* installing *source* package ‘Rmpfr’ ...
** package ‘Rmpfr’ successfully unpacked and MD5 sums checked
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking mpfr.h usability... no
checking mpfr.h presence... no
checking for mpfr.h... no
configure: error: Header file mpfr.h not found; maybe use --with-mpfr-include=INCLUDE_PATH
ERROR: configuration failed for package ‘Rmpfr’
* removing ‘/home/p274829/Rlibrary/Rmpfr’
Warning message:
In install.packages("razzo/Rmpfr_0.7-2.tar.gz", repos = NULL, type = "source") :
  installation of package ‘razzo/Rmpfr_0.7-2.tar.gz’ had non-zero exit status

**Comment by richelbilderbeek** [comment]
Again, workaround is simple: specify all paths of all temp files.

About Rmpfr on Peregrine:

```
module load MPFR
```

Done!
