### ISSUE TITLE
razzo: tests pass locally, fail on Travis

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#160]
Depends on:

 * [x] #179

So @richelbilderbeek , functions for #147 #148 #149 should be working on my branch. The problem is that I get an error on Travis which I can't really understand. This one:

Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
         stop(msg)
     })
  6: tryCatchList(expr, classes, parentenv, handlers)
  7: tryCatchOne(expr, names, parentenv, handlers[[1L]])
  8: value[[3L]](cond)
  9: stop(msg)
  
  ══ testthat results  ═══════════════════════════════════════════════════════════
  OK: 64 SKIPPED: 7 FAILED: 3
  1. Error: use (@test-collect_esses.R#5) 
  2. Error: use (@test-collect_marg_liks.R#5) 
  3. Error: use (@test-collect_nltt_stats.R#5) 

Since the functions pass tests and checks on my local windows machine, I assume it has to be something to do with the OS and, specifically, in the way different OSes manage the file system. I even tried to install pirouette on the cluster to test it, but I get an error when trying to install the dependency "Rmpfr".

I suppose it will take very short time for you, to give it a check on Linux. :rainbow:

**Comment by richelbilderbeek** [comment]
The reason this test is caused is clear to: the `inst/extdata` files push to the GitHub differ from your local files. 

I've created a nice `.gitignore` for you:

```
# History files
.Rhistory
.Rapp.history
# Session Data files
.RData
# Example code in package build process
*-Ex.R
# Output files from R CMD build
/*.tar.gz
# Output files from R CMD check
/*.Rcheck/
# RStudio files
.Rproj.user/
# OAuth2 token, see https://github.com/hadley/httr/releases/tag/v0.3
.httr-oauth
# knitr and R markdown default cache directories
/*_cache/
/cache/
# Temporary files created by R markdown
*.utf8.md
*.knit.md
.Rproj.user
# Shiny token, see https://shiny.rstudio.com/articles/shinyapps.html
rsconnect/
inst/doc
/*.fasta
/*.nex
/*.xml
/*.xml.state
/*.trees
/*.log
/*.posterior.log
data/
tests/testthat/*.fasta
tests/testthat/*.nex
tests/testthat/*.xml
tests/testthat/*.xml.state
tests/testthat/*.trees
tests/testthat/*.log
tests/testthat/*.posterior.log
vignettes/*.html
vignettes/*.pdf
vignettes/*.R
vignettes/*.fasta
vignettes/*.nex
vignettes/*.xml
vignettes/*.xml.state
vignettes/*.trees
vignettes/*.log
vignettes/*.posterior.log
vignettes/pirouette_*.*
vignettes/razzo_pipeline_cache/
results/
```

Put this content in your branch's `.gitignore` and add-commit-push your `inst/extdata` folder. :+1: 

The problem is unrelated to UNIX, so I remove the tag: I got errors in functions run on Windows as well.

**Comment by richelbilderbeek** [comment]
Hmmm, I could also re-create that data. Will do so, so Giappo can focus on reviewing the pirouette manuscript :rainbow:

**Comment by richelbilderbeek** [comment]
Ah, Giappo write to `inst/extdata` in normal use:

```{r}
create_parameters_files <- function(
  project_folder_name = get_path("razzo_project"),
  # ...
) {
  # ...
}
```

Which should have been this:

```{r}
create_parameters_files <- function(
  project_folder_name = pwd()
  # ...
) {
  # ...
}
```

This for multiple reasons:

 * `inst/exdata` is the data *read* from a package (not written)
 * creation of data in `inst/extdata` will fail on Peregrine
 * creation of data by `razzo_project` in (the expected) pwd fails

**Comment by richelbilderbeek** [comment]
Fixed!
