### ISSUE TITLE
Twin tree should be BD by default

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#161]
**[edit: &TLDR: make it BD, #236]**

Rampal thinks a twin tree should be BD by default (see part of the pirouette manuscript below).

I suggest we do so. Agree?

> An optional step is to generate a 'twin tree' (Fig.~\ref{fig:pipeline}, 1a $\rightarrow$ 1b),
that will be analyzed in the same way as the true tree.
The twin tree has the same topology as the given phylogeny, 
yet its branching times are simulated according to 
the tree prior used by BEAST2 to produce a posterior 
\giovanni{is it true? is it Yule or BD? Please check}
\richel{It is Yule}.
\rampal{
  I think it's better to use BD for more generality. 
  Yule is too limited in the trees it can produce.
}

Why did we chose Yule? Because BEAST2 uses Yule by default.

**Comment by Giappo** [comment]
I think that whatever we decide the most important thing is to create agreement between BEAST2's tree prior and the tree's generative model. That's the entire purpose of twinning: we want BEAST2 to operate on the model we actually used to produce the data.
Right now the default for "twinning_params" is already "twinning_params$twin_model == 'bd'".
What's different is that the function "create_experiment" by default calls "inference_model = beautier::create_inference_model()" and the default of "create_inference_model" is "tree_prior = create_yule_tree_prior()".
This leads to an inconsistency when calling the pipeline with defaults.
However if we twin, to make a fair comparison, we need to impose that the analysis on the two pipelines is carried on in the same way, hence the tree prior for the inference model should be the same.
These are our options:
1) We disagree with Rampal and we use "yule" all the way. This means producing twins with "yule" and setting the two "inference_params$treeprior" for both true and twin pipeline to be "yule";
2) We agree with Rampal and we use "bd" all the way. This means producing twins with "bd" and setting the two "inference_params$treeprior" for both true and twin pipeline to be "bd";
There are two ways to realize point 2)
2a) We set the default of "create_inference_model" to "tree_prior = create_bd_tree_prior" and we keep the default of "create_twinning_params" to "twin_model = "bd";
2b) We leave the default of "create_inference_model" to "tree_prior = create_yule_tree_prior" but we add a check on create_pir_params in such a way that when "twinning_params != NA" it has to set by default the "inference_model$tree_prior" to be the same as "twinning_params$twin_model"

I personally prefer option 2), but I think that the last word on the choice between 2a) and 2b) should be yours, as you are the creator of the package.

Additional question: what about "alignment_params"? Is there also a sort of tree_prior? Is it set to bd? Can it be changed?

**Comment by Giappo** [comment]
Twin tree should be taken from df$tree_prior (df is the output of pir_run).
See #185 #186

**Comment by richelbilderbeek** [comment]
Thanks for the overview, you are completely spot-on!

Let's reply to those options:

> 2a) We set the default of "create_inference_model" to "tree_prior = create_bd_tree_prior" and we keep the default of "create_twinning_params" to "twin_model = "bd";

As the babette maintainer, I will not do this: babette follows BEAST2 which uses Yule.

2b) We leave the default of "create_inference_model" to "tree_prior = create_yule_tree_prior" but we add a check on create_pir_params in such a way that when "twinning_params != NA" it has to set by default the "inference_model$tree_prior" to be the same as "twinning_params$twin_model"

Thanks to your work, I think setting the twinning model to `import_from_mainline` by default would resolve all problems?

**Comment by Giappo** [comment]
import_from_mainline should be already the default.
In case you cannot import from the mainline (for example when best candidate tree prior is not yule or bd) the twin tree prior become bd by default.
Perhaps we must add something to be sure that bd is not called when another tree prior is used in the inference.
One possibility is to impose that inference models used in model selections cannot include tree priors available in twinning, if twinning_params != NA

**Comment by richelbilderbeek** [comment]
Done!
