### ISSUE TITLE
Give error if `model_type == "candidate"` and `run_if = "always`

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#176]
**[edit: removed old text, thanks #236]**

Give error if `model_type == "candidate"` and `run_if = "always`

Write a test that verifies this.

**Comment by richelbilderbeek** [comment]
Not a UNIX Issue anymore: it just needs to give an error.

**Comment by Giappo** [comment]
Ok, let's try to break this down:
We have 2^3 = 8 possibilities:

run_if & model_type & do_measure_evidence & possible?
"always" & "generative" & TRUE & not on windows (yes on linux)
"always" & "generative" & FALSE & yes
"always" & "candidate" & TRUE & not on windows (yes on linux)
"always" & "candidate" & FALSE & not allowed
"best_candidate" & "generative" & TRUE & not on windows (yes on linux)
"best_candidate" & "generative" & FALSE & not_allowed
"best_candidate" & "candidate" & TRUE & not on windows (yes on linux)
"best_candidate" & "candidate" & FALSE & not_allowed

Is this what we want?

**Comment by Giappo** [comment]
@richelbilderbeek in pir_run there is a test called
"two candidates, run both"
which creates two candidate experiments and wants to run both.
To do so, it has to select:
model_type = "candidate"
run_if = "always"
which is in theory not allowed by this issue.
Shall I delete the test? Do you prefer if I change "always" to "best_candidate"?

**Comment by Giappo** [comment]
Well, in the meanwhile I'll set it to "best_candidate". In case you don't like it lemme know.

**Comment by richelbilderbeek** [comment]
> "two candidates, run both"

Test for that situation can be deleted. It does not follow the rule to survive #236 :feelsgood:

**Comment by richelbilderbeek** [comment]
Your overview list is awesome!
