### ISSUE TITLE
razzo: revive script-friendly functions create_nltt_stats_file, create_esses_file, create_marg_liks_file and create_fig_1_file

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#183]
In scripts 7-10 in [razzo_project](https://github.com/richelbilderbeek/razzo_project/tree/master/scripts), I see the files `create_nltt_stats_file.R` , `create_esses_file.R`, `create_marg_liks_file.R` and `create_fig_1_file.R`, (and their tests) have been buried.

Could these be unburied?

**Comment by richelbilderbeek** [comment]
I think @Giappo would enjoy this form of time travelling (people make jokes about this form of time travalling and Friesland [1])

 * [1] Q: It's red and travels 100 years back in time? A: the train to Friesland

**Comment by Giappo** [comment]
Good one. Poor fries people :D

**Comment by Giappo** [comment]
Renamed every "create_*_file" to "save_*".

**Comment by richelbilderbeek** [comment]
Cool, well done :+1:
