### ISSUE TITLE
pirouette: implement 'import_from_main_pipeline'

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#185]
Progress:

 * [x] Write code
 * [ ] Write test

**[edit: this Issue has evolved quite a bit, into being about `import_from_main_pipeline`]**

**Comment by Giappo** [comment]
I think that the tree prior used for twinning should definitely be the one selected as best candidate.
We can set it up in pir_run, right after: 

if (!beautier::is_one_na(pir_params$twinning_params)) {

We should insert something like:

pir_params$twinning_params$twin_model <- df$tree_prior

The only problem is that we need to add new twin_models to create_twin_tree, namely: CBS, CCP, CEP.
Yesterday you told me that there is a function that can do it very easily.
If you are ok with that tell me what function it is, create tests to have the result you desire (make very strict tests, please) and I will do the rest.

**Comment by richelbilderbeek** [comment]
I find it hard to understand why at the end of a day, but I assume you thought about it deeply, so I'd say you go ahead :+1:

**Comment by richelbilderbeek** [comment]
Actually, I think this is easy to make optional, something like:

```{r}
create_twinning_params(
  twin_model = "best_candidate
)
```

If you could implement that, I think it would be cool to add it to the article as well :+1: :+1: :+1:

**Comment by Giappo** [comment]
> I find it hard to understand why at the end of a day, but I assume you thought about it deeply, so I'd say you go ahead

@richelbilderbeek Give a read to the last version of the twinning paragraph in the article. I tried to explain it better there.

**Comment by richelbilderbeek** [comment]
Doing a recap on that, I understand one wants to use the generative inference model I used in the true tree, as well as in the twin tree. You were working on an option with value `import_from_mainline` and I do see the point :sunglasses:

I think we already implicitly decided that you go add that feature :+1:

**Comment by Giappo** [comment]
Waiting for Travis to confirm. If so, I will push to develop. In case, please test if it works in the way we want, even in presence of model selection (which is something I cannot do).

**Comment by richelbilderbeek** [comment]
>  In case, please test if it works in the way we want, even in presence of model selection (which is something I cannot do).

Travis will happily test the model selection, so if Travis is happy, we -no, the whole :earth_africa: - can be happy :rainbow:

**Comment by richelbilderbeek** [comment]
OK, I've found the code:
```r
create_pir_params_twin <- function(
  pir_params,
  pir_out
) {
  # ...

  # same tree prior
  if (pir_params$twinning_params$twin_model == "import_from_main_pipeline") {
    if (pir_out$tree_prior %in% get_twin_models()) {
      pir_params_twin$twinning_params$twin_model <- pir_out$tree_prior
    } else {
      pir_params_twin$twinning_params$twin_model <- "birth_death"
    }
  }
  #...
}
```

I could not find any test.

**Comment by richelbilderbeek** [comment]
I will write the tests, after checking if this is the most pressing Issue.

**Comment by richelbilderbeek** [comment]
I suggest in #235 to remove this feature altogether.

**Comment by richelbilderbeek** [comment]
No, kill Issues with rule in #236
