### ISSUE TITLE
pirouette: allow twinning with different tree prior than specified in the generative model

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#186]
I think we should allow the user to twin with a different tree prior as he/she assumed to be part of the generative model. I do see it makes less sense, but I am afraid we might block our users from doing what they want.

This is also related to #185, in which a user is allowed to twin **without** a generative model. 

@Giappo: what do you think about this?

**Comment by Giappo** [comment]
see #185

**Comment by richelbilderbeek** [comment]
Currently, the user can specify a tree prior for the twin tree. I think that's great! At #185 I suggest to add the option `best_candidate` to use the best candidate model's tree prior. I enjoy having both options!

**Comment by richelbilderbeek** [comment]
This is indeed similar to #185, where the option `import_from_mainline` is added. Here I suggest another option: `best_mainline_candidate`.

OTOH, I do think it is of low priority.

**Comment by richelbilderbeek** [comment]
As of today, I find no `best_mainline_candidate` in the code.

Well, this Issue is of low priority, move it back to 'To do'

**Comment by richelbilderbeek** [comment]
No need for this Issue: killing Issues with rule in #236
