### ISSUE TITLE
pirouette: add pir_to_pics

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#203]
Currently, the `pirouette` article handcrafts the figure with scripts from `pirouette_article/scripts`. Maybe it would be better to add a `pirouette` function that does exactly this in a more controlled fashion.

**Comment by richelbilderbeek** [comment]
Hi @Giappo, I think you would agree this is an Issue. Without me working out this Issue in detail, would you -assuming you agree- would you enjoy doing this?

If you need more detailed ideas on how to do this, let me know :+1:

**Comment by Giappo** [comment]
I tried to work with the scripts and they don't work because there is a problem in file paths. Honestly I don't want to go crazy for something like this.
I assign you on this.

**Comment by richelbilderbeek** [comment]
Stress-testing this with `pirouette_article/scripts` scripts.
