### ISSUE TITLE
pirouette: make possible to run pir_run on peregrine [SOLVED]

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#214]
If pirouette could run also on the cluster then also a poor windoes user could test calls that involve model selection with candidates other than the generative model.
At the moment a call of pir_run executed on peregrine will return this error:

Error: all(file.exists(output_log_filename)) is not TRUE
In addition: Warning messages:
1: In file.rename(from = from, to = output_log_filename) :
  cannot rename file 'alignment_a371254a7202.log' to '/local/tmp/RtmpkMOxgr/beast2_a3717a4b7c45.log', reason 'Invalid cross-device link'
2: In file.rename(from = from, to = to) :
  cannot rename file 'alignment_a371254a7202.trees' to '/local/tmp/RtmpkMOxgr/beast2_a37157196bbftrees', reason 'Invalid cross-device link'

Any idea on why this is happening?

**Comment by richelbilderbeek** [comment]
This is a known Issues (#152).

Workaround is simple: specify all paths of all temp files.

As far as I remember, within `pirouette` and `razzo` all paths are specified, but now you know how to help if I've overlooked one :+1:

**Comment by Giappo** [comment]
pirouette and razzo are plenty of predefined paths.
I suppose you worked this already for you, somehow.
Do you have a script where you did it already for pirouette?

**Comment by richelbilderbeek** [comment]
I think [this pirouette_article script for ERQ 2](https://github.com/richelbilderbeek/pirouette_article/blob/master/scripts/example_2.R) will satisfy your needs :rainbow: 

```
################################################################################
# Settings to run on Peregrine cluster
################################################################################
pir_params$alignment_params$fasta_filename <- file.path(root_folder, paste0("example_", example_no, "_true.fasta"))
for (i in seq_along(pir_params$experiments)) {
  pir_params$experiments[[i]]$beast2_options$input_filename <- file.path(root_folder, paste0("example_", example_no, "_beast2_input.xml"))
  pir_params$experiments[[i]]$beast2_options$output_log_filename <- file.path(root_folder, paste0("example_", example_no, "_beast2_output.log"))
  pir_params$experiments[[i]]$beast2_options$output_trees_filenames <- file.path(root_folder, paste0("example_", example_no, "_beast2_output.trees"))
  pir_params$experiments[[i]]$beast2_options$output_state_filename <- file.path(root_folder, paste0("example_", example_no, "_beast2_output.xml.state"))
  pir_params$experiments[[i]]$errors_filename <- file.path(root_folder, paste0("example_", example_no, "_error.csv"))
}
pir_params$evidence_filename <- file.path(root_folder, paste0("example_", example_no, "_evidence_true.csv"))
if (!is_one_na(pir_params$twinning_params)) {
  twinning_params$twin_tree_filename <- file.path(root_folder, paste0("example_", example_no, "_twin.tree"))
  twinning_params$twin_alignment_filename <- file.path(root_folder, paste0("example_", example_no, "_twin.fasta"))
  twinning_params$twin_evidence_filename <- file.path(root_folder, paste0("example_", example_no, "_evidence_twin.csv"))
}
################################################################################
```

**Comment by richelbilderbeek** [comment]
I'll take over here now :rainbow:. Done!
