### ISSUE TITLE
Fix pirouette 'Twinning' vignette

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#224]
I see in [this Travis build log](https://travis-ci.org/richelbilderbeek/pirouette/builds/504830285#L1774) that the vignette `Twinning` fails on @Giappo's branch.

@Giappo: I hope you'll take a look and fix it. I'd enjoy getting your work merged to develop :+1:

**Comment by Giappo** [comment]
It should be fixed now. Waiting for Travis to confirm it.

**Comment by richelbilderbeek** [comment]
Travis is happy, the :world_map: is happy :+1:
