### ISSUE TITLE
create_all_experiments must have an argument to exclude an inference model

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#227]
Currently, `create_all_experiments` creates 40 experiments.

In the pirouette article, I'd enjoy to write:

```r
candidate_experiments <- create_all_experiments(
  exclude_model = generative_experiment$inference_model
)
```

In that context, `create_all_experiments` creates 39 experiments, as it excludes one inference model (which is the generative inference model).

Add the argument `exclude_model` to `create_all_experiments` to be able to exclude one inference model. By default, `exclude_model` must be NA, which indicates that no inference model must be excluded.

**Comment by Giappo** [comment]
What are the criteria to establish that one experiment is the same as the generative? Site model, clock model and tree prior only? Or do we require that everything has to be the same (e.g. mcmc)?

**Comment by Giappo** [comment]
I set it up in such a way site model, clock model, tree prior and mcmc have to be the same. In case, it excludes.
I close the issue. Reopen it if you're not satisfied.
