### ISSUE TITLE
to_twin_filename fails on filenames with two dots

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#231]
BEAST2 uses filenames with two dots in it, e.g. `my.xml.state`. The `xml` indicates the format is XML, the `state` indicates it is a BEAST2 state. Both `xml` and `state` should thus remain the same.
Converting this filename to its twin should thus result in `my_twin.xml.state`. 

Instead, this is converted to the incorrect `my.xml_twin.state`.

I've added a test for this:

```r
test_that("use on filesnames with two dots", {
  skip("#231)
  created <- to_twin_filename("example_3_beast2_output.xml.state")
  expected <- "example_3_beast2_output_twin.xml.state"
  expect_equal(expected, created)
})
```

**Comment by richelbilderbeek** [comment]
Instead of fixing this, I want @Giappo to be the sole author of as much functions as possible. I guess he'll enjoy fixing this on Thursday :+1:

**Comment by Giappo** [comment]
Question: considering that we are only using snake_case variable names, is it ok if I set it before the first dot?

Side note: I can do it with no problems, but I don't really care who authorize more functions. This is not a challenge.
Our only goal is to make things work right in the shortest time possible.

**Comment by richelbilderbeek** [comment]
Well done!
