### ISSUE TITLE
Remove DDD::roundn

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#232]
I see the idea of using `DDD::roundn`. It is caused by the binary representation of floating point numbers. In approxately 1 in 2^16 we get a floating point value rounded off in a way unexpected for humans.

I suggest we let computers be computers and prefer using base R, as it is not worth it.

This reminds me of these NetLogo FAQs:

![2019-03-19-112815_1920x1056_scrot](https://user-images.githubusercontent.com/2098230/54599100-3b012480-4a3a-11e9-96d3-1a58fcb7a2d2.png)

Poor NetLogo maintainer :rainbow:

**Comment by richelbilderbeek** [comment]
Removed `DDD::roundn` from the `create_twin_tree` tests:
 
```r
context("test-create_twin_tree")

dist_nodes <- function(tree, precision = 12) {
  round( # No need of DDD::roundn here
    ape::dist.nodes(tree),
    digits = precision
  )
}
```

**Comment by Giappo** [comment]
Do you know that this might affect the possibility that two aligned branching times will not recognized as such?
