### ISSUE TITLE
If multiple experiments, generative is either first or absent

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#237]
* [x] write tests
 * [x] produce error
 * [x] add to documentation

If there are multiple experiments, generative is either first or absent. Give an error if this is not the case.

Write tests that expect an error if:

 * two experiments, both generative
 * two experiments, first candidate, then generative
 * 40 experiments, 39 candidates first, then generative

Also: add this to the documentation.

Just for completeness, things that should keep working (and hopefully are already tested):

 * one experiment, generative
 * one experiment, candidate [1]
 * two experiments, generative first, candidate second [1]
 * two experiments, both candidates
 * 40 experiments, generative first, 39 candidates second

[1] not a wise choice by the user, but acceptable

**Comment by Giappo** [comment]
What if we instead create a function called "combine_experiments" which takes a vector of experiments and/or list of experiments and combines them in such a way the first is always the generative, if generative is present?
If we don't do so how can a user create an "experiments" list putting the generative as first?

**Comment by richelbilderbeek** [comment]
I enjoy the idea. The Rule of Ruthlessness (#236), however, forces me to say no :godmode:.

Closing the Issue :+1:
