### ISSUE TITLE
Improve pir_plot?

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#284]
I had to use pir_plot lines to build razzo's plot function and I noticed one part that maybe is improvable:

```
tree_and_model_labels <- c(
    tg_label,
    wg_label,
    tb_label,
    wb_label
  )
```
into:

```
  tree_and_model_labels <- c(
    "true_generative" = tg_label,
    "twin_generative" = wg_label,
    "true_candidate" = tb_label,
    "twin_candidate" = wb_label
  )
```

I think this helps to be more safe about what we are actually plotting.

**Comment by Giappo** [comment]
What do you think @richelbilderbeek ?

**Comment by richelbilderbeek** [comment]
Using a map/dictionary like this seems fine to me. Go ahead and add it :+1:

**Comment by richelbilderbeek** [comment]
I think Giappo is happy with this, so I'll close it for him.
