### ISSUE TITLE
Make sure that all the exported functions have examples

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#306]
With help("pirouette") you can access all the exported functions in the package.
Make sure that each and every function in the list have examples.

**Comment by richelbilderbeek** [comment]
@Giappo: I assume you've seen that the build failed, due to examples that fail. You can run these with `devtools::run_examples()`.

**Comment by Giappo** [comment]
@richelbilderbeek thank you

**Comment by richelbilderbeek** [comment]
I assume [this commit](a4bb1b871ad711cfd50fc1a3303bf0330ae6ec57) finished this Issue, closing it.
