### ISSUE TITLE
Do we need "create_ideal_tree"?

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#307]
With a quick research in the package it is possible to find that the string "create_ideal_tree" is present only in the file "create_ideal_tree.R" and "test-create_ideal_tree" (plus, obviously, the NAMESPACE and the documentation of the function).
It appears to be not used anywhere.
Shall we remove the function from the package?
I'd say yes...

**Comment by richelbilderbeek** [comment]
Yes please! :+1:
