### ISSUE TITLE
Check test-errorses_to_data_frame

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#308]
Checking the documentation of all functions in the package I found a new one called "errorses_to_data_frame". To understand what it does I looked into its test script and I could only find ":-(", which I interpreted as a bad thing.
Therefore I wrote a STUB of the test for the above mentioned function.
I didn't write the original function myself, so I might have misinterpreted the correct way of testing it.
I suggest the original creator of the function to give it a look ^^

**Comment by Giappo** [comment]
BTW, I am using the same code for the example. Just to let you know.

**Comment by richelbilderbeek** [comment]
Will do so on Monday

**Comment by richelbilderbeek** [comment]
Good job! Although I did some minor revisions, it was easy with the bulk written down :+1:
