### ISSUE TITLE
Unexpected error distributions

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#309]
[Text from Progress Report week 31 2019]
 
**[edit: For pirouette article's example 3, the error distribution was unexpected:**] 
figure 'The expected error distribution'
shows the error distributions as expected, in which the twins have
a lower median error.

![20190801_expected](https://user-images.githubusercontent.com/2098230/62463408-38edf700-b78a-11e9-8f33-cc56131a34a9.png)

Figure 'An unexpected error distribution' shows the same
error distribution, in which a twin alignment has exactly as
much mutations as the true alignment. This allows BEAST2
to work with as much in genetic information (i.e. mutations)
for its inference.

![20190801_unexpected](https://user-images.githubusercontent.com/2098230/62463409-38edf700-b78a-11e9-9120-b9d858e1f301.png)

 *  :no_entry_sign: Hypothesis 1

[...] My first thought would be that the number
of mutations of the twin would be so much as to scramble
the alignment to noise, making that alignment *less* informative,
resulting in bigger inference errors.

**[edit: Rejected by [this comment](https://github.com/richelbilderbeek/pirouette/issues/309#issuecomment-518973519)]**

 *  [x] Hypothesis 2

A second hypothesis is that in the twinning pipeline,
for the BEAST2 inference, the wrong alignment is used,
see figure 'Wrong alignment used in twin inference?'.
Note how much the posteriors look alike. 

![20190801_appendix_annotated](https://user-images.githubusercontent.com/2098230/62463450-5753f280-b78a-11e9-9fbd-21344080b738.png)

**[edit: this was the one, see [this comment](https://github.com/richelbilderbeek/pirouette/issues/309#issuecomment-519002359)]**

 *  :no_entry_sign: Hypothesis 3

A third option would be that the true tree is used to generate
a twin alignment, in combination with a higher mutation rate
based on the (rightfully) twin tree. See figure 'Wrong tree used in
twin alignment?'

![20190801_full_pipeline](https://user-images.githubusercontent.com/2098230/62463451-57ec8900-b78a-11e9-8302-73b965a33047.png)

**[edit: rejected by [this comment](https://github.com/richelbilderbeek/pirouette/issues/309#issuecomment-518987364)]**

**Comment by Giappo** [comment]
How many original trees have been used to produce this?
How big are the posteriors?
What parameters did you use to simulate the original trees?

**Comment by richelbilderbeek** [comment]
> How many original trees have been used to produce this?

1

> How big are the posteriors?

1000 states

> What parameters did you use to simulate the original trees?

I took an artificial one, as used in the article.

**Comment by richelbilderbeek** [comment]
Or in short: this is the pirouette article example 3.

**Comment by richelbilderbeek** [comment]
Giappo 'Salvo Montalbano' is on the case :male_detective:

**Comment by Giappo** [comment]
How do we set how many trees we have in the posterior?
Is there an easy way to access the phylogenies instead of having directly the errors?

**Comment by richelbilderbeek** [comment]
> How do we set how many trees we have in the posterior?

The MCMC chain determines this. In this example, MCMC chain length is 1111k, burn-in 10% and samping interval 1k. 1111k - 10% = 1M, 1M / 1k = 1000 states. 

> Is there an easy way to access the phylogenies instead of having directly the errors?

This is an excellent point! I discover: yes, there used to be a way (in [pirouette_example_9](https://github.com/richelbilderbeek/pirouette_example_9/tree/master/example_9_314) you can see the .trees files). Same repo, but develop branch does have the `.trees` file anymore.

I'll fix that now ...

**Comment by Giappo** [comment]
I am trying a customized pir_run myself. I reduced the number of trees to consider but then I obtain this:
"
Error in alignment_params_to_posterior_trees(alignment_params = alignment_params,  : 
Mismatch between number of trees and expected number of trees. 
Number of trees (read from .trees file): 1001 
Expected number of trees: 101 
.trees filename: C:/Users/P274829/AppData/Local/Temp/RtmpAnfNZe/file560c3b128e7_twin.trees 
MCMC chain length: 1000000 
MCMC store_every: 10000 
Maybe .trees file of older experiment is used? 
"
Is it not supposed to generate new trees in a different directory at each run?

**Comment by richelbilderbeek** [comment]
> Is it not supposed to generate new trees in a different directory (or at least with a different .trees file name) at each run?

You are right: it should! No idea how that can be :confused:: temporary filenames *should* definitely be unique. To make it worst: when you do `create_beast2_option`, there is an `overwrite` argument, which is `TRUE` by default as well :confused:

**Comment by richelbilderbeek** [comment]
I've fixed [https://github.com/richelbilderbeek/pirouette_example_9](https://github.com/richelbilderbeek/pirouette_example_9). You can now see the raw data in the `example_9_314` folder.

**Comment by Giappo** [comment]
Is there a way to visualize posterior trees just using pirouette functions?
I'd prefer not to stick to example 9 and to test different settings to see what's going on. To do that I need to break down every part of the pirouette routine and check the values at intermediate steps also, e.g. checking posterior trees before evaluating the error.

**Comment by richelbilderbeek** [comment]
> Is there a way to visualize posterior trees just using pirouette functions?

From `pirouette::pir_to_pics` I simplify to:

```
  # Posteriors
  first_experiment <- utils::head(pir_params$experiments, n = 1)[[1]]
  
  # True, gen
  if (first_experiment$inference_conditions$model_type == "generative") {
    filename <- file.path(folder, "true_posterior_gen.png")
    grDevices::png(
      filename = filename,
      width = 1000, height = 800
    )
    babette::plot_densitree(
      phylos = tracerer::parse_beast_trees(
        first_experiment$beast2_options$output_trees_filenames
      ),
      alpha = 0.01,
      consensus = consensus,
      cex = 2.0,
      scaleX = TRUE,
      scale.bar = FALSE
    )
    grDevices::dev.off()
  }
```

which means probably you're looking for `babette::plot_densitree`.

> I'd prefer not to stick to example 9 and to test different settings to see what's going on. To do that I need to break down every part of the pirouette routine and check the values at intermediate steps also, e.g. checking posterior trees before evaluating the error.

Sure, sounds like a fine approach to me as well.

Happy hunting!

**Comment by Giappo** [comment]
Maybe Montalbano solved the mystery.
Apparently we just produced an "unlucky" random twin tree.
To prove that I unwrapped pir_run and, starting from the phylogeny provided in example 3, generate a distribution of twins. Then I pir_plotted all of them.
Here is the script:
`
# general setting
chain_length <- 5e4
store_every <- 1e3
phylogeny_example_3 <- ape::read.tree( # taken from example 3
    text = "(((A:8, B:8):1, C:9):1, ((D:8, E:8):1, F:9):1);"
); plot(phylogeny_example_3)

max_seed <- 30
pir_outs <- vector("list", max_seed)
for (seed in 1:max_seed) {
  print(seed)

  # generate "true" phylogeny
  true_phylogeny <- phylogeny_example_3
  # set.seed(seed); n_taxa <- 20; true_phylogeny <- ape::rcoal(n = n_taxa); rm(.Random.seed, envir=globalenv())
  # true_phylogeny <- mbd::mbd_sim(
  #   pars = c(0.1, 0.1, 4, 0.3), # best
  #   # pars = c(0.1, 0.1, 2, 0.2), # good
  #   # pars = c(0.2, 0.1, 0.8, 0.1), # worse
  #   seed = seed
  # )$reconstructed_tree; rm(.Random.seed, envir=globalenv())

  # Select all experiments with 'run_if' is 'always'
  experiment <- create_experiment(
    inference_conditions = create_inference_conditions(
      model_type = "generative",
      run_if = "always",
      do_measure_evidence = FALSE
    ),
    inference_model = create_inference_model(
      mcmc = create_mcmc(chain_length = chain_length, store_every = store_every)
    )
  )
  experiments <- list(experiment)
  
  twinning_params <- create_twinning_params(
    rng_seed_twin_tree = seed,
    rng_seed_twin_alignment = seed
  )
  
  pir_params <- create_pir_params(
    alignment_params = create_test_alignment_params(),
    experiments = experiments,
    twinning_params = twinning_params
  )
  
  # TRUE routine
  # Simulate the true alignment and save it to file
  create_alignment_file(
    phylogeny = true_phylogeny,
    alignment_params = pir_params$alignment_params,
    verbose = pir_params$verbose
  )
  
  # Estimate evidences if needed
  beautier::check_file_exists(pir_params$alignment_params$fasta_filename, "fasta_filename")
  marg_liks <- est_evidences(
    fasta_filename = pir_params$alignment_params$fasta_filename,
    experiments = pir_params$experiments,
    evidence_filename = pir_params$evidence_filename,
    verbose = pir_params$verbose
  )
  
  # Select the experiments
  experiments <- select_experiments(
    experiments = pir_params$experiments,
    marg_liks = marg_liks, # For most evidence
    verbose = pir_params$verbose
  )
  testit::assert(length(experiments) > 0)
  
  # Measure the errors per inference model
  errorses <- list() # Reduplicated plural, a list of errors
  i <- 1
  experiment <- experiments[[i]]
  
  errorses[[i]] <- phylo_to_errors(
    phylogeny = true_phylogeny,
    alignment_params = pir_params$alignment_params,
    error_measure_params = pir_params$error_measure_params,
    experiment = experiment,
    verbose = pir_params$verbose
  )
  
  # Create a sub-sub-sub folder, don't warn when it already exists
  dir.create(
    dirname(experiment$errors_filename),
    showWarnings = FALSE, recursive = TRUE
  )
  utils::write.csv(
    x = errorses[[i]],
    file = experiment$errors_filename
  )
  beautier::check_file_exists(experiment$errors_filename)
  
  pir_out_true <- errorses_to_data_frame(
    errorses = errorses,
    experiments = experiments,
    marg_liks = marg_liks
  )
  pir_out_true$tree <- "true"
  pir_out_true$tree <- as.factor(pir_out_true$tree)
  pir_out_true
  
  # TWIN routine
  twin_phylogeny <- create_twin_tree( # nolint pirouette function
    phylogeny = true_phylogeny,
    twinning_params = pir_params$twinning_params
  )
  
  # Save twin tree
  twin_tree_filename <- pir_params$twinning_params$twin_tree_filename
  # Create a sub-sub-sub folder, don't warn when it already exists
  dir.create(
    dirname(twin_tree_filename),
    showWarnings = FALSE, recursive = TRUE
  )
  ape::write.tree(phy = twin_phylogeny, file = twin_tree_filename)
  beautier::check_file_exists(twin_tree_filename, "twin_tree_filename")
  
  # Create twin alignment file
  create_twin_alignment_file(
    twin_phylogeny = twin_phylogeny,
    alignment_params = pir_params$alignment_params,
    twinning_params = pir_params$twinning_params
  )
  
  # Select the alignment file for model comparison
  fasta_filename <- pir_params$twinning_params$twin_alignment_filename
  beautier::check_file_exists(fasta_filename, "fasta_filename")
  
  # Select the evidence filename the model comparison is written to
  evidence_filename <- pir_params$twinning_params$twin_evidence_filename
  
  # Estimate evidences (aka marginal likelihoods) if needed
  # marg_liks will be NULL if this was unneeded, for example, when
  # interested in the generative model only
  marg_liks <- est_evidences(
    fasta_filename = fasta_filename,
    experiments = pir_params$experiments,
    evidence_filename = evidence_filename,
    verbose = pir_params$verbose
  )
  
  # Select the experiments
  # to do inference with
  experiments <- select_experiments(
    experiments = pir_params$experiments,
    marg_liks = marg_liks, # For most evidence
    verbose = pir_params$verbose
  )
  testit::assert(length(experiments) > 0)
  
  # Measure the errors per inference model
  errorses <- list() # Reduplicated plural, a list of errors
  i <- 1
  experiment <- experiments[[i]]
  
  experiment$beast2_options$input_filename <- to_twin_filename(experiment$beast2_options$input_filename) # nolint indeed too long ...
  experiment$beast2_options$output_log_filename <- to_twin_filename(experiment$beast2_options$output_log_filename) # nolint indeed too long ...
  experiment$beast2_options$output_trees_filenames <- to_twin_filename(experiment$beast2_options$output_trees_filenames) # nolint indeed too long ...
  experiment$beast2_options$output_state_filename <- to_twin_filename(experiment$beast2_options$output_state_filename) # nolint indeed too long ...
  experiment$errors_filename <- to_twin_filename(experiment$errors_filename) # nolint pirouette function
  
  errorses[[i]] <- phylo_to_errors(
    phylogeny = twin_phylogeny,
    alignment_params = pir_params$alignment_params,
    error_measure_params = pir_params$error_measure_params,
    experiment = experiment,
    verbose = pir_params$verbose
  )
  
  # Create a sub-sub-sub folder, don't warn when it already exists
  dir.create(
    dirname(experiment$errors_filename),
    showWarnings = FALSE, recursive = TRUE
  )
  utils::write.csv(
    x = errorses[[i]],
    file = experiment$errors_filename
  )
  beautier::check_file_exists(experiment$errors_filename, "errors_filename")
  
  pir_out_twin <- errorses_to_data_frame(
    errorses = errorses,
    experiments = experiments,
    marg_liks = marg_liks
  )
  pir_out_twin$tree <- "twin"
  pir_out_twin$tree <- as.factor(pir_out_twin$tree)
  pir_out_twin
  
  # TOTAL output
  pir_out <- rbind(pir_out_true, pir_out_twin)
  # pir_out
  pir_outs[[seed]] <- pir_out
  # pir_plot(pir_out)
}

for (seed in seq_along(pir_outs)) {
  temp <- unname(pir_outs[[seed]][grepl(x = colnames(pir_outs[[seed]]), pattern = "error")])
  if (seed == 1) {
    errors <- temp
  } else {
    errors <- cbind(errors, temp)
  }
}
colnames(errors) <- paste0("error_", 1:ncol(errors))
testit::assert(ncol(errors) == max_seed * ncol(temp))
all_errors <- cbind(pir_outs[[seed]][, 1:6], errors)
pir_plot(all_errors)
`
This is the output for "max_seed" = 30.

![montalbano_strikes_again](https://user-images.githubusercontent.com/14541948/62482536-ae22f180-b7b5-11e9-9423-6191a6224038.png)

You can play with the script to check yourself, changing "max_seed" or "chain_length" or "store_every". Note that the argument "seed" is parsed in 

`
  twinning_params <- create_twinning_params(
    rng_seed_twin_tree = seed,
    rng_seed_twin_alignment = seed
  )
`

to guarantee a distribution of independent twin trees.

**Comment by Giappo** [comment]
@richelbilderbeek since all the code is unwrapped, please check if I made any mistakes in the configuration of the pir_params (for example in the inference_model, of which I am not 100% sure).

**Comment by richelbilderbeek** [comment]
That is great news! I think you've made a convincing point that the twin on average has lower errors and that we (again!) had bad luck with the RNG. 

Code looks fine, we can be sure `pirouette` is prone to correct us if we made a mistake. It does expose that the `pirouette` software architecture can be improved from a programmers' point of view.

I'll re-run some pirouette examples and check the `razzo` results as well to prove we've had bad RNG.

Thanks!

**Comment by richelbilderbeek** [comment]
@Giappo: I am sorry for us to get rid of the illusion of this figure:

![Just an illusion](https://user-images.githubusercontent.com/14541948/62482536-ae22f180-b7b5-11e9-9423-6191a6224038.png)

This illusion is caused by this line:

```r
chain_length <- 5e4
```

To have trust in a result, we need to have an Effective Sample Size of 200, that is, we need at least 200 uncorrelated samples. If `store_every` (aka sampling interval) is 1e3, we need at least an MCMC of length 2e5. 

It does not mean that we could have had bad RNG, it means only it is proven we get good RNG for ESSes of 5 in a location where the MCMC algorithm hasn't converged yet...

You want to run your work for MCMC chain length of 1e6 on your computer? I am currently running pirouette examples and the last razzo run, so my CPUs are occupied.

**Comment by Giappo** [comment]
To be honest, I expect to find kind of the same result even with 1e6 cl. I will run a smaller test now to get an idea and a full test overnight.

**Comment by richelbilderbeek** [comment]
Would be nice. 

I observe that for [pirouette_example_9](https://github.com/richelbilderbeek/pirouette_example_9/tree/develop) a different RNG seed results again in the twin having a higher median error, so I am running a third time...

**Comment by Giappo** [comment]
I made a quick test and even with cl=1e6 the computation is fast enough, so I am trying with 50 tress now. The preliminary test, as forecasted, was successful btw.

**Comment by Giappo** [comment]
> Would be nice!
> 
> I observe that for [pirouette_example_9](https://github.com/richelbilderbeek/pirouette_example_9/tree/develop) a different RNG seed results again in the twin having a higher median error, so I am running a third time...

One option, actually, could be to use more seeds even for pirouette paper. In the end the calculation is fast enough and tbh I would find it more accurate because I think a single random tree doesn't really make much sense.

**Comment by richelbilderbeek** [comment]
So [pirouette_example_9](https://github.com/richelbilderbeek/pirouette_example_9) has had 'bad RNG' for three out of three times. I find that hard to believe.

My hypothesis is that your unwrapped code does right what `pirouette` currently does wrong.

**Comment by Giappo** [comment]
Computation is finished: I'll paste the code and the outcome.
The code is shorter, using directly pir_run (but doing essentially the same thing). This time I wanted to test using different seeds, just to be sure that the previous result was due to the 1st 50 seeds. The code is:
`
chain_length <- 1e6
store_every <- 1e3
phylogeny_example_3 <- ape::read.tree( # taken from example 3
    text = "(((A:8, B:8):1, C:9):1, ((D:8, E:8):1, F:9):1);"
); plot(phylogeny_example_3)

max_seed <- 50
pir_outs <- vector("list", max_seed)
for (seed in 1:max_seed) {
  print(seed)
  set.seed(seed)
  twin_seed <- sample(x = 1:1e5, size = 1)

  # generate "true" phylogeny
  true_phylogeny <- phylogeny_example_3
  pir_params <- create_pir_params(
    alignment_params = create_test_alignment_params(),
    experiments = list(create_experiment(
      inference_conditions = create_inference_conditions(
        model_type = "generative",
        run_if = "always",
        do_measure_evidence = FALSE
      ),
      inference_model = create_inference_model(
        mcmc = create_mcmc(
          chain_length = chain_length,
          store_every = store_every
        )
      )
    )),
    twinning_params = create_twinning_params(
      rng_seed_twin_tree = twin_seed,
      rng_seed_twin_alignment = twin_seed
    )
  )
  pir_outs[[seed]] <- pir_run(
    phylogeny = true_phylogeny,
    pir_params = pir_params
  )
}

for (seed in seq_along(pir_outs)) {
  temp <- unname(pir_outs[[seed]][grepl(x = colnames(pir_outs[[seed]]), pattern = "error")])
  if (seed == 1) {
    errors <- temp
  } else {
    errors <- cbind(errors, temp)
  }
}
colnames(errors) <- paste0("error_", 1:ncol(errors))
testit::assert(ncol(errors) == max_seed * ncol(temp))
all_errors <- cbind(pir_outs[[seed]][, 1:6], errors)
pir_plot(all_errors)
`

The result is:
![montalbano_strikes_again](https://user-images.githubusercontent.com/14541948/62538421-0b20b500-b853-11e9-9b24-fcfb113c6da8.png)

To me it looks like it works perfectly fine.

PS: I would suggest to change pir_plot in such a way the output is less "smooth" and more "bin-like", as Rampal suggested for the razzo paper. If you are ok with that I can open an issue and start to work on that.

**Comment by Giappo** [comment]
> So [pirouette_example_9](https://github.com/richelbilderbeek/pirouette_example_9) has had 'bad RNG' for three out of three times. I find that hard to believe.
> 
> My hypothesis is that your unwrapped code does right what `pirouette` currently does wrong.

The wrapped version does the same. Check the code in the previous comment.

**Comment by richelbilderbeek** [comment]
Blimey, your work does look convincing! 

But how do you explain 3x 'bad RNG' in [pirouette_example_9](https://github.com/richelbilderbeek/pirouette_example_9) then? You predict if I run it more often, things will get better?

**Comment by richelbilderbeek** [comment]
I will run your work on my computer, just to see ...

**Comment by richelbilderbeek** [comment]
I used only 5 seeds, but I do get the similar results:

![montelbano_strikes_again_and_again](https://user-images.githubusercontent.com/2098230/62539918-9ea7b500-b856-11e9-9a37-d482921e6447.png)

**Comment by richelbilderbeek** [comment]
> PS: I would suggest to change pir_plot in such a way the output is less "smooth" and more "bin-like", as Rampal suggested for the razzo paper. If you are ok with that I can open an issue and start to work on that.

I think that's a good idea! Go ahead :+1:

**Comment by Giappo** [comment]
> One option, actually, could be to use more seeds even for pirouette paper. In the end the calculation is fast enough and tbh I would find it more accurate because I think a single random tree doesn't really make much sense. You could use this kind of argument to prove that lottery is a good investment, for example.

@richelbilderbeek what about this?

**Comment by richelbilderbeek** [comment]
> One option, actually, could be to use more seeds even for pirouette paper. In the end the calculation is fast enough and tbh I would find it more accurate because I think a single random tree doesn't really make much sense. You could use this kind of argument to prove that lottery is a good investment, for example.

Agreed: we'll use as much seeds as there is time within the span of my PhD.

**Comment by richelbilderbeek** [comment]
This Issue is still unresolved: currently, only the Montelbano script yields the expected results, where all pirouette examples (and I also checking the last razzo run) give unexpected results.

**Comment by richelbilderbeek** [comment]
Montelbano strikes again...

![and_again](https://user-images.githubusercontent.com/2098230/62541209-a0bf4300-b859-11e9-950d-543481500d77.png)

**Comment by Giappo** [comment]
> > One option, actually, could be to use more seeds even for pirouette paper. In the end the calculation is fast enough and tbh I would find it more accurate because I think a single random tree doesn't really make much sense. You could use this kind of argument to prove that lottery is a good investment, for example.
> 
> Agreed: we'll use as much seeds as there is time within the span of my PhD.

We do not need many seeds. I think 20 or 30 (50 max, I'd say) are enough to drastically improve the quality of the result. The time required is extremely short, so I don't really see any downside...

**Comment by Giappo** [comment]
> Montelbano strikes again...
> 
> ![and_again](https://user-images.githubusercontent.com/2098230/62541209-a0bf4300-b859-11e9-950d-543481500d77.png)

Does this mean that it works? Please write it, because every time you say it doesn't work it makes me extremely nervous :D

**Comment by richelbilderbeek** [comment]
> Does this mean that it works?

The Montelbano script works as expected, where everything else doesn't, e.g. the couple-minutes-fresh result of [pirouette_example_3](https://github.com/richelbilderbeek/pirouette_example_3) are bad as well.

So what does the Montelbano script do right, what the pirouette examples do wrong...

Still waiting for the razzo results analysis (my computer apparently is much slower than yours), will keep you updated.

**Comment by richelbilderbeek** [comment]
> We do not need many seeds. I think 20 or 30 (50 max, I'd say) are enough to drastically improve the quality of the result. The time required is extremely short, so I don't really see any downside...

We can use any number of seeds, as long as it fits with my PhD span. I can predict run-times on Peregrine and I do think these are longer than your local :dragon: computer.

**Comment by Giappo** [comment]
The "Montalbano" is very minimalistic so, for the Occam's razor, I'd assume it yields much more trustworthy results. My feeling is that there's a bug somewhere in the example scripts...

**Comment by richelbilderbeek** [comment]
> My feeling is that there's a bug somewhere in the example scripts...

That is one of my hypotheses as well:

  1. all pirouette examples have a bug in the scripts, although all of them worked on week ago
  2. the Montelbano script uses a default setting that makes it overly simplistic

Looking at what the scripts do differently would resolve this :seedling:

**Comment by richelbilderbeek** [comment]
Ah, it think it's the Montelbano script that is too simplistic (and it also explains why it runs so fast):

```r
    alignment_params = create_test_alignment_params(),
```

this creates a DNA alignment of 4 base pairs.

Will re-run the Montelbano script with 1k base pairs...

**Comment by richelbilderbeek** [comment]
@Giappo: for a DNA alignment of 1000 base pairs, Montelbano loses:

![montelbano_loses](https://user-images.githubusercontent.com/2098230/62548441-14b41800-b867-11e9-8cd2-54743fa69e78.png)

That bring us -sadly- back to square one.

**Comment by richelbilderbeek** [comment]
That the twin gives an error distribution with a higher median is replicated in a whole `razzo_project` run, from [these results](http://richelbilderbeek.nl/razzo_project_20190801.zip).

![figure_1](https://user-images.githubusercontent.com/2098230/62556765-e2f67d80-b875-11e9-9a4a-2a5edc1632e7.png)

**Comment by Giappo** [comment]
> That bring us -sadly- back to square one.
> 
> ![damn](https://user-images.githubusercontent.com/2098230/62549550-f94a0c80-b868-11e9-911f-546aade65287.png)

PORCODIO!

**Comment by Giappo** [comment]
The question is then: why with 4 bp you have one thing, and with 1000 you get something completely different?

**Comment by Giappo** [comment]
Ok, so I pondered a bit about it. I don't know if this is the cause but a difference between 4 and 1000 bp is the following.
Imagine to have two cases: one with 2 (to simplify) base pairs and another with 3.
Case 1: In the first case we have on average 2 mutations. They can occur in the following scenarios:
((2, 0), (1, 1), (0, 2)) with frequencies (1, 2, 1). If one nucleotide undergoes 2 mutations (cases 1 and 3) then 1 time out of 3 it falls back in the original state (e.g. to simplify let's imagine a root sequence "aa". In scenario 1 this can become "xa" at the 1st mutation and the 2nd mutation has 1/3 possibility to revert in state "aa"). So scenarios 1 and 3 have probabilities 1/2 and in 1/3 of the cases you revert back to the original state. So 1/6 of the times nothing changes.
Case 2: We have 3 mutations (on average). Again:
Scenarios: ((3, 0), (2, 1), (1, 2), (0, 3)) with frequencies (1, 3, 3, 1) (basically a Pascal's triangle). Cases 2 and 3 cannot revert back to the original root sequence (say "aaa"). Case 1 and 4 can, each with probability (2/3) * (1/3) = 2/9 (a -> x -> (y!=a) ->a). Total probability to revert back to root sequence is then (2/8) * (2/9) = 4/72 = 1/18. This probability is smaller than the equivalent for Case 1.
This makes me think that as we increase the sequence length this probability reduces by a big big factor due to a fast increase in entropy.
In general I expect the sequence to become more and more homogeneous as the sequence lenght increases. I am wondering if this can explain the difference that we see or if there is more...

**Comment by Giappo** [comment]
Plus, I wonder if we calculate the desired mutation rate in the right way. To do so we need to consider the total branch length of the tree.
Tomorrow I will check if we actually do so (I leave this here also as a reminder for myself).

**Comment by richelbilderbeek** [comment]
I would say it has nothing to do with mutation rates being too high and that hypothesis 1 can be discarded:

> [...] the number
> of mutations of the twin would be so much as to scramble
> the alignment to noise, making that alignment less informative,
> resulting in bigger inference errors.

Would this hypothesis be the case, lowering a mutation rate would result in less errors in the twin.

Here I've run [https://github.com/richelbilderbeek/pirouette_example_9](https://github.com/richelbilderbeek/pirouette_example_9) with mutation rate 10x lower, of `0.1 / crown_age = 0.1 / 10 = 0.01`:

![errors_low_mut_rate](https://user-images.githubusercontent.com/2098230/62602274-ab2e1b00-b8f3-11e9-9290-9cc69bf32c00.png)

Here are three runs with a default mutation rate of `1 / crown_age = 1 / 10 = 0.1`:

![errors](https://user-images.githubusercontent.com/2098230/62602420-019b5980-b8f4-11e9-9e51-f6962571c3f7.png)


![errors](https://user-images.githubusercontent.com/2098230/62602406-f9dbb500-b8f3-11e9-9605-1304a1602fe8.png)


![errors](https://user-images.githubusercontent.com/2098230/62602393-ed575c80-b8f3-11e9-9df8-ec4622f9fb83.png)

Because the errors in the twin remain more or less the same, hypothesis 1 can be discarded.

**Comment by richelbilderbeek** [comment]
Hypothesis 3 can be tested easily:

> A third option would be that the true tree is used to generate
a twin alignment, in combination with a higher mutation rate
based on the (rightfully) twin tree. See figure 'Wrong tree used in
twin alignment?'

Simply let `create_twin_alignment(_file)?` show the Newick of the input tree.

**Comment by richelbilderbeek** [comment]
Can reject hypothesis 3, as the twin tree *is* a twin tree:

```
richel@sonic:~/GitHubs/pirouette_example_9$ Rscript example_9.R
[1] "DEBUG: Creating a twin alignment based on phylogeny (((A:2.4039324,B:2.4039324):2.00355172,C:4.40748412):5.59251588,((D:0.45088325,E:0.45088325):0.20803191,F:0.65891516):9.34108484);'"
```

**Comment by richelbilderbeek** [comment]
Already in the code, I can see that hypothesis 2 is true:

```r
pir_run_twin_tree <- function(
  # ...
){
  # ...

    errorses[[i]] <- phylo_to_errors(
      phylogeny = twin_phylogeny,
      alignment_params = pir_params$alignment_params,
      error_measure_params = pir_params$error_measure_params,
      experiment = experiment,
      verbose = pir_params$verbose
    )
```

`phylo_to_errors` does not get the `twinning_params`, but uses the `alignment_params` only.

**Comment by richelbilderbeek** [comment]
Hypothesis 2 was the one:

> A second hypothesis is that in the twinning pipeline,
for the BEAST2 inference, the wrong alignment is used,

![errors](https://user-images.githubusercontent.com/2098230/62608289-e46c8800-b8ff-11e9-810b-046b58793e30.png)

Closing this Issue

**Comment by richelbilderbeek** [comment]
![de_cock](https://user-images.githubusercontent.com/2098230/62609140-7aed7900-b901-11e9-8701-82749be98bd5.png)

**Comment by richelbilderbeek** [comment]
What I dislike, is that I 'just fixed it', instead of writing a test for it to prevent it from happening again in the future :disappointed:

**Comment by richelbilderbeek** [comment]
Note that I describe in the code that it is 'a dirty hack' and how to clean it up.

**Comment by Giappo** [comment]
@richelbilderbeek great job! Now I can sleep at night again <3

**Comment by richelbilderbeek** [comment]
Yup, *we* can sleep at night again :sleepy:.
