### ISSUE TITLE
Allow to specify site and clock model used in alignment simulation

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#31]
Currently, the alignment is always simulated with a JC69 site model and a strict clock model. Allow the user to pick a different site and clock model.

**Comment by richelbilderbeek** [comment]
Taking a look at [the phangorn::simSeq documentation](https://rdrr.io/cran/phangorn/man/simSeq.html), I think @Giappo would enjoy doing this Issue :+1:

Model|Mutation rates between nucleotides
---|---
JC69|All equal
HKY|?
TN93|?
GTR|All different

**Comment by Giappo** [comment]
Where do I recover the base frequencies?

**Comment by Giappo** [comment]
Site models should be in. They still need a way to differentiate base frequencies which, as of now, are set to 0.25 all the time.
I checked the phangorn::simSeq documentation and unfortunately I couldn't find anything about clock model.

**Comment by Giappo** [comment]
Now base frequencies are taken from the root sequence.
Clock model has not been implemented as I have no idea where to put it.
It you want me to do it give additional info about it. Otherwise close this issue.

**Comment by richelbilderbeek** [comment]
You're right, one cannot specify a clock model in `phangorn::simSeq` :astonished: !

So, site model is done, will create a seperate Issue for clock model, closing this one :rainbow:
