### ISSUE TITLE
Make "pir_plot" bin-like

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#312]
In the last Rampal's comment on razzo figure he suggested to make the plot bin-like. We can do the same with pirouette.

**Comment by Giappo** [comment]
@richelbilderbeek What about this? Do you like it?

![new_pir_plot](https://user-images.githubusercontent.com/14541948/62542250-b897c680-b85b-11e9-97e5-0122e0b5eaca.png)

**Comment by richelbilderbeek** [comment]
I think this is a good first step, but I did like the old one better, as it was more obvious at the intersection of the curves where they were:

![issue_312](https://user-images.githubusercontent.com/2098230/62542979-37413380-b85d-11e9-80f5-db6ff8697e13.png)

Sure, with a nice smooth curve like this one can infer it is the lower one, but that will not always be the case.

If you find a way to increase the contrast between the two distributions, I'd be even more pleased :+1:

**Comment by Giappo** [comment]
What if we change the color from pale pink to something with a higher contrast?

**Comment by richelbilderbeek** [comment]
Whatever works :+1:

**Comment by Giappo** [comment]
@richelbilderbeek this is the current output. If you are satisfied with that you can close the issue. Otherwise tell me what you would change.
![new_pir_plot](https://user-images.githubusercontent.com/14541948/62705325-769e8a00-b9ed-11e9-911c-aa320603a920.png)

**Comment by richelbilderbeek** [comment]
Pretty! :+1:

Will happily close :rainbow:
