### ISSUE TITLE
Think of three names for nodeSub models

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#335]
If done, I (@richelbilderbeek) will create the stubs.

:+1:

**Comment by richelbilderbeek** [comment]
That's a neat first step! Calling the site models `linked` and `unlinked`, however, may not cover the nodeSub model completely. Or do you think `linked_node_sub` and `unlinked_node_sub` describe the model best?

**Comment by thijsjanzen** [comment]
I was more thinking of `node_sub_linked` and `node_sub_unlinked` ... 
But I will consider using a bit more explosive language... tbc

**Comment by richelbilderbeek** [comment]
`node_sub_linked` and `node_sub_unlinked` it will be.

**Comment by richelbilderbeek** [comment]
I already dislike the computer-y names, shouldn't it be `linked_node_sub` and `unlinked_node_sub`, as that is closer to English?

@thijsjanzen would `linked_node_sub` and `unlinked_node_sub` be valid names?

**Comment by richelbilderbeek** [comment]
Sorry to have bothered Thijs, `linked_node_sub` and `unlinked_node_sub` it will be.

**Comment by thijsjanzen** [comment]
Oops! Forgot about this. 
I really like linked_node_sub and unlinked_node_sub, thank you!
