### ISSUE TITLE
Cannot create branching times for a Yule tree

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#342]
`pirouette` provides for the creation of Yule twin trees, thus it should be possible to create a set of branching times for a Yule tree. A Yule tree has, by definition, an extinction rate of zero.

Whenever I use that knowledge to call `create_twin_branching_times` I get an error:

```
Error in tess.sim.taxa.age.constant(n, nTaxa, age, lambda, mu, massExtinctionTimes,  : 
  Invalid parameter values for lambda and mu!
```

Here is the test to reproduce the error with:

```r
test_that("use", {

  skip("Cannot create branching times for a Yule tree, #342")
  phylogeny <- ape::read.tree(text = "(((A:1, B:1):1, C:2):1, D:3);")

  # Error in this statement
  yule_branching_times <- create_twin_branching_times(
    seed = 314,
    lambda = 0.0,
    mu = 1.0,
    phylogeny = phylogeny,
    n_replicates = 1,
    method = "random_tree"
  )
  bd_branching_times <- create_twin_branching_times(
    seed = 314,
    lambda = 0.1,
    mu = 1.0,
    phylogeny = phylogeny,
    n_replicates = 1,
    method = "random_tree"
  )
  expect_equal(yule_branching_times, bd_branching_times)
})
```

There are many ways to solve this.

 * Modify `create_twin_branching_times` to provide for an extinction rate of zero
 * (my favorite) Write two new functions, `create_twin_yule_branching_times` and `create_twin_bd_branching_times`

Good luck :+1:

**Comment by richelbilderbeek** [comment]
As the man that eats branching times for breakfast, I assign @Giappo to this one :+1:

**Comment by Giappo** [comment]
@richelbilderbeek I do not understand this issue. For two reason:

1) If you want a yule process you need to set the parameters in such a way that lambda > 0 and mu = 0. In the example you proposed lambda = 0 and mu > 0. I do not see how this can be working.

2) Why would you expect a yule process and a bd process to have the same branching times? Different processes are expected to return different branching times.

My take on this is: this test is not correct. If you want me to do something else write a test and I will work on it.

**Comment by richelbilderbeek** [comment]
> If you want a yule process you need to set the parameters in such a way that lambda > 0 and mu = 0. In the example you proposed lambda = 0 and mu > 0. I do not see how this can be working.

You are indeed right: I switched `lambda` and `mu`! I will create another Issue to rename these to `speciation_rate` and `extinction_rate`.

Closing this Issue, sorry for the noise :+1:
