### ISSUE TITLE
Create idealized BD tree for article

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#35]
See [pirouette_article](https://github.com/richelbilderbeek/pirouette_article/issues/1).

**Comment by richelbilderbeek** [comment]
@Giappo: I think you'll like this one! I assign you the Issue. Sure, hit me with those questions if you have them :+1:

**Comment by Giappo** [comment]
Blimey, the `phangorn::macCladeCred` appears just what we want! Will use it :+1:

**Comment by Giappo** [comment]
Depends (at least partially) on issue #56

**Comment by richelbilderbeek** [comment]
Agree. I hope you like my suggestion there, at #56 :rainbow:

**Comment by Giappo** [comment]
As I said [here ](https://github.com/richelbilderbeek/pirouette_article/issues/1#issuecomment-463644095), we already have some very sexy tree figures. Can we close this?

**Comment by richelbilderbeek** [comment]
I checked the manuscript and found:

```
We start with an idealised birth-death tree of five taxa and a crown age of 10:

% Need idealised birth-death tree
% From https://github.com/richelbilderbeek/pirouette_article/issues/1
% and https://github.com/richelbilderbeek/pirouette/issues/35
\begin{lstlisting}[language=R, floatplacement=H, frame=single]
phylogeny <- ape::read.tree(text = "((A:4, B:4):1, (C:4, D:4):1);")
\end{lstlisting}
```

The phylogeny is clearly not an ideal one. I'd love to see your most ideal, Miss-Universe-perfection tree there. I think you already wrote a function to create these, so this should be easy :+1:

**Comment by Giappo** [comment]
Now you have the most stunning tree ever created in living memory.
I close this.

**Comment by richelbilderbeek** [comment]
I saw it. I loved it :heart:.

It is indeed the most stunning tree ever created in living memory :heart_eyes: !
