### ISSUE TITLE
peregrine must use new babette interface

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#351]
In the old days, one would write:

```r
bbt_run(
  beast2_options(
    output_log_filename = "out.log",
    output_trees_filenames = "out.trees
)
```

These two files, however, have been an inherent part of a `beautier` MCMC object.

Nowadays one writes:

```r
bbt_run(
  inference_model = create_mcmc(
    tracelog = create_tracelog(
      filename = "out.log"
    ),
    treelog = create_treelog(
      filenames = "out.trees
    )
  )
)
```

Make peregrine use the new interface.

**Comment by richelbilderbeek** [comment]
I hope @Giappo will help me with this one...

**Comment by Giappo** [comment]
Hi Richel,

There is one thing I do not understand. 
I just updated babette calling:

`devtools::install_github("ropensci/babette")`

If I call the help from "bbt_run" I obtain this:

`
bbt_run(fasta_filename, tipdates_filename = NA,
  site_model = beautier::create_jc69_site_model(),
  clock_model = beautier::create_strict_clock_model(),
  tree_prior = beautier::create_yule_tree_prior(), mrca_prior = NA,
  mcmc = beautier::create_mcmc(),
  beast2_input_filename = beastier::create_temp_input_filename(),
  rng_seed = 1,
  beast2_output_state_filename = beastier::create_temp_output_state_filename(),
  beast2_path = beastier::get_default_beast2_path(), overwrite = TRUE,
  verbose = FALSE, beast2_output_log_filename = "deprecated",
  beast2_output_trees_filenames = "deprecated",
  beast2_working_dir = "deprecated", fasta_filenames = "deprecated",
  site_models = "deprecated", clock_models = "deprecated",
  tree_priors = "deprecated", mrca_priors = "deprecated",
  posterior_crown_age = "deprecated", cleanup = "deprecated")
`
As you can see there is no "inference_model" section. So how can I use the new one?

**Comment by richelbilderbeek** [comment]
The new one is called `bbt_run_from_model` :+1:

Enjoy!

**Comment by richelbilderbeek** [comment]
AFAICS: Well done @Giappo!

Closing the Issue :+1:
