### ISSUE TITLE
pirouette::sim_bd_twin_tree must have no 'seed' argument 

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#353]
Currently, `pirouette::sim_bd_twin_tree` has a seed argument. I enjoy the idea (did I put it in?), but I think it should be removed: `pirouette` will set the RNG seed before simulating a twin tree. I suggest to keep letting `pirouette` do that.

Additionally, the resulting behavior is weird: if I call a `sim_something` function twice (with all default params) I expect different results.

&TLDR; remove the `seed` argument in the `pirouette::sim_bd_twin_tree` function

**Comment by richelbilderbeek** [comment]
I think @Giappo will enjoy this one :+1:

**Comment by Giappo** [comment]
@richelbilderbeek 
"sim_bd_twin_tree" at some point will make this call

  # generate bd branching times from the inferred parameters
  bd_brts0 <- pirouette::create_twin_branching_times(
    phylogeny = phylogeny,
    lambda = lambda_bd,
    mu = mu_bd,
    n_replicates = n_replicates,
    method = method
  )

If no seed is provided by the function this call cannot work. I am actually surprised that this has worked so far.
Question: if no seed is passed to the function "sim_bd_twin_tree", what's the seed to pass to "create_twin_branching_times"? Do I have to remove the argument seed also from this function (as I personally suppose) or do I have to provide a seed (somehow)?

**Comment by Giappo** [comment]
Ok, so I modified pirouette removing the seed also from create_twin_branching_times.
My reasoning is that in the process of creating a twin tree (which should not need any seed), the creation of the branching times is a part of it, so it should follow the general principle of the function that generates the entire tree. The contrary would go against the principle that you expose in the issue.
I hope it's fine. If it is not please tell me (and therefore how it should be done instead) and I will fix it in the way you want.
🌈

**Comment by richelbilderbeek** [comment]
> Question: if no seed is passed to the function "sim_bd_twin_tree", what's the seed to pass to "create_twin_branching_times"? 

Apparently, seed does nothing and can be safely removed.

> Do I have to remove the argument seed also from this function (as I personally suppose) or do I have to provide a seed (somehow)?

You did the right thing. Thanks :+1:
