### ISSUE TITLE
test-sim_twin_alignment does not pass locally on Windows

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#357]
If I try to run the test on my local pc I obtain this:

-- 1. Failure: use, twin has less info (@test-sim_twin_alignme
     pirouette::count_n_mutations(alignment = true_alignment, root_sequence = root_sequence) not equal to pirouette::count_n_mutations(alignment = twin_alignment, root_sequence = root_sequence).
     1/1 mismatches
     [1] 20 - 17 == 3

The number of mutations on the true alignment is 20 whereas on the twin alignment we have 17.
Question: the name of the test is "use, twin has less info". Do we need to have "expect_gt" instead of "expect_equal"? If yes, why the twin has less information?

**Comment by Giappo** [comment]
In the test we also have 
`
twinning_params <- pirouette::create_twinning_params(
    sim_twin_alignment_fun =
      pirouette::get_sim_twin_alignment_with_same_n_mutation_fun(
        max_n_tries = 1
      )
  )
`
which seems to suggest that we only perform 1 try and therefore we expect to not necesseraly reach the number of mutations we require. Why do we perform this test? What's out goal?

**Comment by richelbilderbeek** [comment]
> Why do we perform this test? What's [the] goal?

To test if the function `create_twinning_params` can be called with `get_sim_twin_alignment_with_same_n_mutation_fun` without giving errors.

The function `sim_twin_alignment_with_same_n_mutation` already tests the number of mutation matches.

**Comment by richelbilderbeek** [comment]
I predict I've fixed it. Closing :+1:
