### ISSUE TITLE
Rename `(un)linked_node_sub` to `uns` and `lns`

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#362]
@lintr-bot is right, some function names are too long. Therefore, it is time to:

 * rename `linked_node_sub` to `lns`
 * rename `unlinked_node_sub` to `uns`
 * do this for both the function names as well as the filenames

In that way a function like `sim_true_alignment_with_linked_node_sub_site_model` becomes
`sim_true_alignment_with_lns_site_model`, which is close to the already existing `sim_true_alignment_with_std_site_model`.

Good luck :+1:

**Comment by richelbilderbeek** [comment]
I think @Giappo would enjoy this one :+1:

**Comment by Giappo** [comment]
What about this?

`
testit::assert(site_model != "linked_node_sub")
  testit::assert(site_model != "unlinked_node_sub")
`

**Comment by richelbilderbeek** [comment]
@Giappo: the example you have given:

```r
testit::assert(site_model != "linked_node_sub")
testit::assert(site_model != "unlinked_node_sub")
```

will become:

```r
testit::assert(site_model != "lns")
testit::assert(site_model != "uns")
```

Good luck :+1:

**Comment by richelbilderbeek** [comment]
Will take this one over, thanks @Giappo for his current work.

**Comment by richelbilderbeek** [comment]
Done!
