### ISSUE TITLE
Rename 'lambda' and 'mu' to 'speciation_rate' and 'extinction_rate'

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#366]
In [Issue 342](https://github.com/richelbilderbeek/pirouette/issues/342#issuecomment-558032985) I expected a Yule tree to be generated from a BD process with `lambda`/`mu` equals to zero. I swapped the interpretation of these symbols.

Instead of using `lambda` and `mu`, use `speciation_rate` and `extinction_rate`, as these are directly expressing what they are.

**Comment by richelbilderbeek** [comment]
I think @Giappo would enjoy this (very simple) one :+1:

**Comment by Giappo** [comment]
@richelbilderbeek speciation and extinction rates are universally named, respectively, lambda and mu in pretty much the entire field. I think we can live with that.

**Comment by richelbilderbeek** [comment]
Nah, I would enjoy to change it. Will assign myself then.

**Comment by thijsjanzen** [comment]
I agree with Giappo, across CRAN, universally lambda and mu are used for speciation and extinction rate.

Consider the packages:
TreeSim  (sim.bd.taxa and related functions)
TESS       (tess.sim.taxa and related functions)
DDD        (dd_sim and related functions)
RPANDA (the function fit_bd)


However, ape, apTreeshape and geiger use 'b' and 'd'

**Comment by richelbilderbeek** [comment]
I am personally more interested in readability: if '[any symbol]' denotes an extinction rate, call it 'extinction_rate'.

**Comment by richelbilderbeek** [comment]
For reference, [this video from Kevlin Henney](https://vimeo.com/146380156) at 31:16: 'Name things what they are':

![screen](https://user-images.githubusercontent.com/2098230/69613344-b5eef600-1031-11ea-8084-60c30d1a2623.png)

**Comment by richelbilderbeek** [comment]
Well let pass, for now.
