### ISSUE TITLE
Replace 'true_alignment' by 'tral', 'twin_alignment' by 'twal'

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#369]
[lintr-bot](https://github.com/richelbilderbeek/pirouette/commit/afa317077e5ed68b900d601df6595f9762b8720a) is right to call our function names too long.

I suggest to rename the following parts of function names:
 
From|To|Example
---|---|---
`true_alignment`|`tral`|`​get_sim_true_alignment_with_lns_site_model_fun` -> `​get_sim_tral_with_lns_site_model_fun`
`twin_alignment`|`twal`|`​get_sim_twin_alignment_with_lns_site_model_fun` -> `​get_sim_twal_with_lns_site_model_fun`

@Giappo: would you agree with this rename, and if no, what do you suggest?

**Comment by richelbilderbeek** [comment]
If @Giappo agrees, go ahead and assign me or keep yourself assigned to this Issue :+1:

**Comment by richelbilderbeek** [comment]
OK, will shorten this now...

**Comment by richelbilderbeek** [comment]
Hmmm, I think replacing `site_model` by `nsm` (Nucleotide Substitution Model) will already help a bunch.

**Comment by richelbilderbeek** [comment]
It did, but not enough. Need to replace 'true_alignment' by 'tral', 'twin_alignment' by 'twal'

**Comment by richelbilderbeek** [comment]
Closing the vote. Let's go :+1:

**Comment by thijsjanzen** [comment]
looking through the code, I noticed that 'nsm' is NOT used for 'Node Substitution Model', as I expected. 
I suggest this be changed to 'sm' (Substitution Model'). Dropping the nucleotides part should be fine, given that nucleotides are substituted is obvious for all intents and purposes of this package I think.

**Comment by richelbilderbeek** [comment]
Hmmm, I see the confusion. 

As you already noticed, `nsm` means 'Nucleotide Substitution Model' and I preferred it over the `sm` abbreviation as that could mean both 'site model' or 'substitution (of what?) model'.

I do guess you are one of the few that think about node substitutions :grin:. 

Would you agree with this reasoning?

**Comment by richelbilderbeek** [comment]
Or: Yes, I see your point and I do agree. But because the argument runs both ways (to add or omit the `n`), I suggest to keep it as it is.

Fine with that?

**Comment by thijsjanzen** [comment]
> Or: Yes, I see your point and I do agree. But because the argument runs both ways (to add or omit the `n`), I suggest to keep it as it is.
> 
> Fine with that?

Let's leave it at that.
