### ISSUE TITLE
Add: create_dd_tree

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#383]
Similar to `create_yule_tree`, `create_bd_tree` add a function called `create_dd_tree`. It should create a nice exemplary tree.

Also use similar tests as those in `test-create_bd_tree.R`.

**Comment by Giappo** [comment]
What kind of arguments do you want for this function? What is its purpose?

**Comment by richelbilderbeek** [comment]
> What kind of arguments do you want for this function?

As much arguments as `create_yule_tree` except with a carrying capacity added. 

> What is its purpose?

I quote:

> Similar to `create_yule_tree` [...] It should create a nice exemplary tree.

Additionally, I will use it in the manuscript (unless using replicates is doable, which I strongly predict is not).

**Comment by richelbilderbeek** [comment]
@Giappo: cool, thanks!

**Comment by richelbilderbeek** [comment]
There are some corner cases that do not work, I've marked the tests exposing them as such:

```r
  skip("Cases that do not work")
  expect_silent(create_dd_tree(n_taxa = 2, crown_age = 1))
  expect_silent(create_dd_tree(n_taxa = 10, crown_age = 1, extinction_rate = 0.0))
  expect_silent(create_dd_tree(n_taxa = 10, crown_age = 1, best_of_n_trees = 1))
```

**Comment by richelbilderbeek** [comment]
Cool, will check :+1:

**Comment by richelbilderbeek** [comment]
Checked, well done :+1:
