### ISSUE TITLE
Remove geiger

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#391]
At the moment on develop branch, there are no calls to geiger functions. However the package is still included in the DESCRIPTION file and loaded in a test.
I suggest we remove every occurrance of geiger in pirouette (as it is already on the giovanni branch).
If you agree @richelbilderbeek I will proceed.

**Comment by richelbilderbeek** [comment]
TLDR: already fixed :+1:

I've seen your work in removing geiger. It was well done, so it already reached master.

After that, I found out `nodeSub` depends on `geiger` as well, triggering that nasty message, breaking a test. I solved this by adding `geiger` to the DESCRIPTION, yet in the `Suggests` section.

But, indeed, you **can** solve it: just call the function twice!

Blimey, have already fixed this Issue... thanks :+1:
