### ISSUE TITLE
Cache folder name on Windows?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#400]
[This commit](https://github.com/richelbilderbeek/pirouette/commit/71eda31af9387d3fd28d9a8d915d9072e8033722) shows that Windows has a cache folder name that can differ.

Unsure what the consequences of this is.

**Comment by richelbilderbeek** [comment]
I label this a 'debate' Issue, because of its description: 'There is no clear idea of how to proceed'.

**Comment by Giappo** [comment]
I don't know if it can differ. On my system (windows 10) it used to be called "cache" all lowercase.
Maybe we can add a condition like "cache" | "Cache"?

**Comment by richelbilderbeek** [comment]
> Maybe we can add a condition like "cache" | "Cache"?

If that would work, would be great :+1:

**Comment by richelbilderbeek** [comment]
Seems fixed, closing this Issue :+1:
