### ISSUE TITLE
Check 'error_function' argument

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#48]
* [x] in 'check_error_measure_params': 
   check if error_function is indeed a function.
   Test is in check_error_measure_params, in 'use' section.
 * [x] in 'check_error_measure_params': 
   check if error_function is indeed a function with at least 2 parameters.
   Test is in check_error_measure_params, in 'use' section.
 * [x] in 'check_error_measure_params': 
   check if error_function is indeed a function that has a lowest
   value for identical trees.
 
There are test is in `check_error_measure_params`, in 'use' section.

**Comment by richelbilderbeek** [comment]
Just to be sure @Giappo has enough to do, I hope he'll enjoy doing this simple refactoring :+1:

If not, go ahead and unassign yourself :innocent:

Tip: use `is.function`. 

I do expect questions here, as I have not written a test to express what I want. If you need a test to be written, assign me this Issue and I'll do,

**Comment by Giappo** [comment]
@richelbilderbeek I suppose that when you say:
"check if error_function is indeed a function with at least 2 parameters."
you mean that the error_functions must have at least to arguments. Am I right?

**Comment by richelbilderbeek** [comment]
Oops, closed accidentally. Sure I'll take a look :+1:

**Comment by richelbilderbeek** [comment]
Added some tests, verified @Giappo did a good job. Well done :+1:
