### ISSUE TITLE
Review pirouette manuscript

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#58]
Thanks @Giappo for the feedback! I processed all of it and added an introduction.

I hope you could you review this new version :1st_place_medal:

**Comment by Giappo** [comment]
Will do after #65.

**Comment by richelbilderbeek** [comment]
Well done, I will do the next iteration :+1:

**Comment by richelbilderbeek** [comment]
@Giappo: are you done? If yes. go ahead and assign me :+1:

**Comment by Giappo** [comment]
Sorry Richel, I forgot to do that.

**Comment by richelbilderbeek** [comment]
OK, I've added the description of how to set up an experiment. Sloppily, so ready for some improvements. I did not review anything else than that. 

As agreed upon, I will assign @Giappo to do a next review on Monday :+1:.

**Comment by richelbilderbeek** [comment]
Thanks for your review, I will do the next one :+1:

**Comment by richelbilderbeek** [comment]
I processed your thoughts into the article, as well as rewroting some rougher parts, re-created figures (I hope you like the Wall Street theme), added discussion. 

Your turn again :ping_pong:

**Comment by Giappo** [comment]
Your turn

**Comment by richelbilderbeek** [comment]
I hope you can take a look before tonight 22:30. I will add the final hand before 23:59 and send it to Rampal. It's not perfect yet, but it's getting awesome!

**Comment by Giappo** [comment]
I've substantially reviewed the manuscript. I think we are moving in the right direction, as now it looks much more clearer to me.
Give it a look and tell me what you think.

**Comment by richelbilderbeek** [comment]
Lookin' great! :+1: 

My turn now :rainbow: :grin:

**Comment by richelbilderbeek** [comment]
Getting better and better! Your turn again!

**Comment by richelbilderbeek** [comment]
As agreed upon, you'll do your table magic, I'll do the text :+1:

**Comment by richelbilderbeek** [comment]
I've added an extra example between the original 3rd and 4th (now the 3rd an 5th), as to better build up the story. The 4th and 5th example can be ignored in the review for now.
