### ISSUE TITLE
Mutation rate can be a function working on a phylogeny

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#59]
Currently, the mutation rate must be a known and constant value, set when creating an alignment params.

If `pirouette` would be given phylogenies of different crown ages, the mutation rate must be re-set each time.

A superior alternative would be to allow the user to specify a function to determine the mutation rate, based on the crown age:

```{r}
create_alignment_params(
  mutation_rate = function(crown_age) { 1.0 / crown_age },
  ...
}
``` 

`pirouette` can then calculate the mutation rate itself in `pir_run`.

The old interface should keep working:

```{r}
create_alignment_params(
  mutation_rate = 0.1,
  ...
}
```

**Comment by richelbilderbeek** [comment]
Just to be sure @Giappo has enough to do, I hope he'll enjoy doing this simple refactoring :+1:

If not, go ahead and unassign yourself :innocent:

Tip: use `is.function`. 

I do expect questions here, as I have not written a test to express what I want. If you need a test to be written, assign me this Issue and I'll do,

**Comment by Giappo** [comment]
Problem: crown_age is not necessarily specified when calling create_alingment_params.
In fact not crown_age nor phylo are specified in standard default inputs.

**Comment by richelbilderbeek** [comment]
Correct! That is *exactly* why it needs to be a function of a phylogeny: pirouette will get a phylogeny from the user and can then use the function to determine a mutation rate from that phylogeny.

So the problem is exactly the point :sunrise_over_mountains: 

If more questions, hit me :godmode:

**Comment by Giappo** [comment]
I will change it in such a way the argument is "phylogeny" and not "crown_age".
It cannot become a default option for create_alignment_params, I think, as in this function's defaults the phylogeny is not present.
I can set it, though, as a default option for pir_run, as you asked. To do so I need to know how to set the other parameters of create_alignment_params, when called to create the default "alignment_params" for pir_run.

Example for pir_run with default arguments:

pir_run <- function(
  phylogeny,
  twinning_params = NA,
  alignment_params = create_alignment_params(
   root_sequence = ???,
   mutation_rate = create_standard_mutation_rate(phylogeny = phylogeny),
   site_model = beautier::create_jc69_site_model(),
   clock_model = beautier::create_strict_clock_model(),
   rng_seed = ???,
   fasta_filename = tempfile(fileext = ".fasta")
  ),
  model_select_params = create_gen_model_select_param(alignment_params), # nolint obsolete, #69
  inference_params = create_inference_params(), # obsolete, #69
  experiments = list(create_experiment()),
  error_measure_params = create_error_measure_params()
)

In this example I leave the defaults that I believe should be the right one for the problem. Please tell me what you desire to choose for ???. In case you want different choices for the others too, please let me know.
Thanks @richelbilderbeek to be so helpful with this :rainbow:

**Comment by richelbilderbeek** [comment]
> It cannot become a default option for create_alignment_params, I think, as in this function's defaults the phylogeny is not present.

You definitely can! The mutation rate can be determined from a function (that uses a phylogeny), on a phylogeny given in the future. That is what makes it so powerful!

```
# Some silly function
my_function <- function(phylogeny) { return 1.0 / ape::Ntip }

pir_run <- function(
  # ...
  alignment_params = create_alignment_params(
    # ...
   mutation_rate = my_function,
    # ...
  ),
  # ...
) {
  # Sim pylogeny
  phylogeny <- someting

  # Sim alignment, call the 'mutation_rate' function
  mutation_rate <- alignment_params$mutation_rate(phylogeny) 
}
```

> Please tell me what you desire to choose for ???

 * `root_sequence`: there is no default `root_sequence` and I think that is a good thing. For tests, I like to use `acgt`.
 * `rng_seed`: I like a default seed of 0, 1, 42, 314 or your favorite number :+1: 

I hope this helps. At least that my helpful reputation is maintained :rainbow:

**Comment by Giappo** [comment]
Problem: if we change the "mutation_rate" from numeric to a function, this will mean that "create_alignment_params" will always need a phylogeny to work. 
Are you really sure this is really what you want?

**Comment by richelbilderbeek** [comment]
You've spotted the problem well. Yes, we as programmers have to check if the `mutation_rate` is a number or function, and act accordingly.

To quote me:

> The old interface should keep working

As you've already discovered `is.function`, this should be a piece of cake for you now :+1:

**Comment by Giappo** [comment]
Now a function can be provided as alignments_params$mutation_rate as long as it will produce the an appropriate mutation rate (numeric and positive)

**Comment by richelbilderbeek** [comment]
I've checked `check_alignment_params` and I liked what I saw :1st_place_medal:

Well done, closing the Issue for you :+1:
