### ISSUE TITLE
Build under Windows

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#71]
Depends on:

 * [x] #69:

I see there are some vignettes that ruthlessly ignore Windows users. No wonder AppVeyor's build does not work. It would be good if a Windows user would try to get 'Check Package' working. If that works, assign me/you to #70 to get it built under AppVeyor.

I think @Giappo would like to express his love for his OS by doing this Issue :rainbow::rainbow::rainbow:

**Comment by richelbilderbeek** [comment]
Travis does not support Windows builds of R yet :neutral_face:

**Comment by Giappo** [comment]
"Check Package" actually works perfectly on windows.
Of course all the vignette parts where mcbette needs to be called are skipped, but it does pass the check.
If you think it's enough we can close the issue.

**Comment by richelbilderbeek** [comment]
That's enough. Thanks for checking :+1: 

Closing the Issue :rainbow:
