### ISSUE TITLE
Add 'pir_params'

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#77]
Now `pir_run` has the foillowing interface:

```{r}
pir_run <- function(
  phylogeny,
  twinning_params = NA,
  alignment_params,
  model_select_params = create_gen_model_select_param(alignment_params), # nolint obsolete, #69
  inference_params = create_inference_params(), # obsolete, #69
  experiments = list(create_experiment()),
  error_measure_params = create_error_measure_params()
)
```

I want to replace this by:

```{r}
pir_run <- function(
  phylogeny,
  pir_params = create_pir_params()
)
```

Reasons are many, among others (1) `raket` and `razzo` can easier pass around information, (2) I need a place to store  the two parameters documented below. 

```
#' ...
#' @param evidence_epsilon relative error in estimating the
#'   evidence (aka marginal likelihood).
#'   TODO: put in \code{misc_params},
#' @param evidence_filename filename to store the estimated
#'   evidences (aka marginal likelihoods)
#' ...
pir_run_tree <- function(
```

Due to this, I request:

 * A `create_pir_params` as below

```{r}
create_pir_params <- function(
  # ... current parameter sets
  evidence_epsilon = 1e-12,
  evidence_filename = tempfile(fileext = ".csv")
)
```

 * A `check_pir_params` as done with `check_experiment`
 * Tests for both, see tests of `create_experiment` and `check_experiment`

No worry about only a partial implementation, just putting the scaffolding into place is enough,

:warning: Do not change anything within `pir_run` yet, I will remove this warning after #69 is resolved

**Comment by richelbilderbeek** [comment]
I think Giovanni would be up for this :+1:

**Comment by Giappo** [comment]
I saw that the label "not yet" has been removed. Does it mean that I can modify pir_run already?

**Comment by Giappo** [comment]
Current defaults for pir_run are:

pir_run <- function(
  phylogeny,
  twinning_params = NA,
  alignment_params,
  model_select_params = create_gen_model_select_param(alignment_params), # nolint obsolete, #69
  inference_params = create_inference_params(), # obsolete, #69
  experiments = list(create_experiment()),
  error_measure_params = create_error_measure_params()
)

As you can see there is no default for alignment_params. In this way a call like:

pir_run <- function(
  phylogeny,
  pir_params = create_pir_params()
)

is not possible. Do you have any suggestion for a default alignment_params?

**Comment by Giappo** [comment]
Now pir_runs is defined in the following way:

pir_run <- function(
  phylogeny,
  pir_params = create_pir_params(
    alignment_params = create_alignment_params(
      mutation_rate = create_standard_mutation_rate(phylogeny)
    )
  )
)

where create_pir_params can accommodate for the arguments "evidence_epsilon " and "evidence_filename " and has the following defaults:

create_pir_params <- function(
  alignment_params,
  twinning_params = NA,
  model_select_params = create_gen_model_select_param(alignment_params), # nolint obsolete, #69
  inference_params = create_inference_params(), # obsolete, #69
  experiments = list(create_experiment()),
  error_measure_params = create_error_measure_params(),
  evidence_epsilon = 1e-12,
  evidence_filename = tempfile(fileext = ".csv")
)

The function pir_run has the following checks at the start of the script:

  if (!beautier::is_phylo(phylogeny)) {
    stop("'phylogeny' must be of class 'phylo'")
  }
  check_pir_params(pir_params)

The body of the function has remained unmodified. The tests and the examples have been rewritten accordingly.
The issue can be probably be closed.

**Comment by richelbilderbeek** [comment]
I'm lovin' it! Thanks :+1:
