### ISSUE TITLE
Pick a default root sequence for alignment params

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#81]
I'm tired of specifying this all the time in `create_alignment_params`

I suggest `pirouette::create_blocked_dna(1000)`.

@Giappo: agreed? 

 * If yes, go ahead and add that default
 * If disagree on root sequence, go ahead and use your favorite
 * If disagree on this idea, go ahead and unassign yourself. I'd be interested in your thoughts :+1:

**Comment by Giappo** [comment]
I don't really have a strong opinion on this.
I'll trust you and execute it in the way you want.

**Comment by richelbilderbeek** [comment]
Thanks :+1:

**Comment by Giappo** [comment]
Ok, I have a question: if we set the default to 1000, don't we risk that tests become uselessly long?
If you really want to set it to 1000 isn't better if we correct every test to use back root_sequence = create_mono_nuc_dna(length = 4) to save time?

**Comment by richelbilderbeek** [comment]
I understand the concern, and I have had the same one. I reasoned like this:

 * default length 4: user must adapt default argument to 1000 
 * default length 1000: we must adapt our tests

As I think we should prefer helping users over ourselves, to set the default to 1000. As we don't have a default yet, all of our tests not already have that length of 4, so I expect nothing to break.

Agree?

**Comment by Giappo** [comment]
I agree. I actually already set all the tests to 4.
