### ISSUE TITLE
Can I remove pir_run_check_inputs?

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#83]
After the introduction of pir_params, the function pir_run starts in this way:

  # Check the inputs
  if (!beautier::is_phylo(phylogeny)) {
    stop("'phylogeny' must be of class 'phylo'")
  }
  check_pir_params(pir_params)

In the light of this I feel like that the function pir_run_check_inputs is redundant. I just wanna know from you if I can delete it.

**Comment by richelbilderbeek** [comment]
Agree, no need to test things twice. Go ahead and delete that `pir_run_check_input` :+1:
