### ISSUE TITLE
Should seed for "create_twin_tree" be different for every twin created?

### ISSUE THREAD

**Issue by Giappo** [richelbilderbeek/pirouette#84]
Now every twin tree is created with seed = 42. This means that they are always generated in the same way and we risk to lose the independence of the trees (which is the key point of the "method" I would like to use).
I suggest to modify create_twin_tree in such a way to include a seed argument. The best way would be to call the same seed from another part of the pipeline (e.g. alignment_params or inference params) which will ensure that all the twin trees will be independent, which looks very important.

**Comment by richelbilderbeek** [comment]
Great idea!

The idea of recycling a parameter is well intended, yet adding the seed to the `twinning_params` seems a more natural fit to me. Try telling your friends that for twinning you not only need twinning parameters, but also an alignment parameter. Also, 'create_twin_tree' tests (in pseudocode) are easier to write/read/do:

```{r}
# Use twinning_params
twinning_params <- ...
phylo <- ...
twin_1 <- create_twin_tree(phylo, twinning_params)
twin_2 <- create_twin_tree(phylo, twinning_params)
expect_equal(twin_1, twin_2)
twinning_params$rng_seed <- twinning_params$rng_seed + 1
twin_2 <- create_twin_tree(phylo, twinning_params)
expect_not_equal(twin_1, twin_2)
```

```
# Recycle
twinning_params <- ...
alignment_params <- ...
phylo <- ...
twin_1 <- create_twin_tree(phylo, twinning_params, alignment_params)
twin_2 <- create_twin_tree(phylo, twinning_params, alignment_params)
expect_equal(twin_1, twin_2)
alignment_params$rng_seed <- alignment_params$rng_seed + 1
twin_2 <- create_twin_tree(phylo, twinning_params, alignment_params)
expect_not_equal(twin_1, twin_2)
```

**Comment by Giappo** [comment]
Now it depends on #108

**Comment by richelbilderbeek** [comment]
I see `create_twinning_params` has an `rng_seed` argument, so I feel this Issue can be closed.

Doing so :+1:
