### ISSUE TITLE
Twin trees' BEAST2 filenames must differ from true trees' BEAST2 filenames 

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/pirouette#95]
Currently, `pir_run` is called on the true trees and on the twin trees **with the same `experiments`**.

This means that `experiment$beast2_options$output_trees_filename` of a true and twin tree are equal.

Make it so that the twin trees' filenames are different, e.g. by adding `_twin` to the filename, i.e. `my_posterior.trees` becomes `my_posterior_twin.trees`.

There are four filenames in `experiment$beast2_options`, do this with all four of them.

```
test_that("generative with twin", {

  # ...

  # Files not yet created
  to_twin_filename <- function(x) x # stub
  if (1 == 2) {
    # Issue 95, #95
    testit::assert(to_twin_filename("1.csv") == "1_twin.csv")
  }

  # ...
})
```

**Comment by richelbilderbeek** [comment]
Yes, something non-UNIX for @Giappo! I think he'll enjoy this one :+1:

**Comment by Giappo** [comment]
@richelbilderbeek 
Do you with all of these four elements to be changed in the way you told me?

$`input_filename`
[1] "C:\\Users\\P274829\\AppData\\Local\\Temp\\Rtmp2PVvYl\\file48382b235653.xml"

$output_log_filename
[1] "C:\\Users\\P274829\\AppData\\Local\\Temp\\Rtmp2PVvYl\\file483821066dfc.log"

$output_trees_filenames
[1] "C:\\Users\\P274829\\AppData\\Local\\Temp\\Rtmp2PVvYl\\file4838437d16d8.trees"

$output_state_filename
[1] "C:\\Users\\P274829\\AppData\\Local\\Temp\\Rtmp2PVvYl\\file483869602271.xml.state"

**Comment by Giappo** [comment]
I applied "to_twin_filename" to all elements of "experiment$beast2_options" whose names are containing the word "filename".
In case there I misunderstood let me know.

**Comment by richelbilderbeek** [comment]
Works like a breeze! Well done :+1:
